WITH updates(name, domain, priority) AS (VALUES
('500 Global', '500.co', ''),
('100 Accelerator', '100accelerator.com', ''),
('1849 bio', '1849.bio', ''),
('2 Strands Biosciences', '2strandsbiosciences.com', ''),
('2S Water', '2swater.com', ''),
('3D BioFibR', '3dbiofibr.com', 'Low'),
('3D BioFibr.', '3dbiofibr.com', ''),
('3Helix', '3helix.com', ''),
('3M', 'mmm.com', ''),
('3R', '3r-t.com', ''),
('4ls Consulting', '4ls-consulting.com', ''),
('500 Global', '500.co', ''),
('5AM Ventures', '5amventures.com', ''),
('9zero', '9zero.com', ''),
('9Zero', 'letsgo.9zero.com', ''),
('A*STAR', 'hq.a-star.edu.sg', ''),
('A*STAR', 'a-star.edu.sg', ''),
('Aarti Pharma Labs', 'aartipharmalabs.com', ''),
('Abalone Bio', 'abalonebio.com', ''),
('ABL Bio', 'ablbio.com/en/company/main', ''),
('Abram Scientific', 'abramscientific.com', 'Medium'),
('AC Biode', 'acbiode.com', ''),
('Accelerated Materials', 'acceleratedmaterials.co', 'Medium'),
('Accor', 'accor.com', ''),
('Acipay Online', 'acipayonline.com', ''),
('Acrobat Genomics', 'acrobatgenomics.com', ''),
('Acrocyte', 'acrocyte.com', ''),
('Activate', 'activate.org', ''),
('Activate', 'activate.org', ''),
('Adapt Capital', 'adaptcapital.com', ''),
('ADB Ventures', 'adbventures.org', ''),
('ADEN Services', 'adenhq.com', ''),
('Adept Materials', 'adeptmaterials.com', 'Low'),
('Advantage Therapeutics', 'advantagetherapeutics.com', ''),
('Aepnus Technology', 'aepnus.com', ''),
('Affinity', 'affinity.co', ''),
('Affix Labs', 'affixlabs.com', ''),
('Agorize', 'agorize.com', ''),
('Agrata', 'agrata.co', 'Medium'),
('AI Therapies', 'ai-therapies.com', ''),
('AirAsia', 'notification.airasia.com', ''),
('AirREGI', 'airregi.jp', ''),
('Airtable', 'airtable.com', ''),
('Airtable', 'mail.airtable.com', ''),
('Ajinomoto Ventures', 'aj-cvc.com', ''),
('Al Riyad', 'alriyad.iq', ''),
('Albatroz Therapeutics', 'albatroztherapeutics.com', ''),
('Alchemist Accelerator', 'alchemistaccelerator.com', ''),
('Alkali Lab', 'alkalilabs.com', 'Medium'),
('Alkali Labs', 'alkalilabs.com', ''),
('Alkemio', 'alkemio.bio', ''),
('Alkemio-bio', 'alkemio.bio', 'Low'),
('Allium Bio', 'alliumbio.com', 'Medium'),
('Allvue Systems', 'allvuesystems.com', ''),
('Alpha Intelligence Capital', 'aicapital.ai', ''),
('AlphaMe', 'alphame.ai', ''),
('Alsop Louie Partners', 'alsop-louie.com', ''),
('Alta Resource Technologies', 'altatech.io', ''),
('Altos Ventures', 'altos.vc', ''),
('Altr', 'altrfltr.com', 'Medium'),
('Amazon', 'amazon.com', ''),
('Amazon', 'leo.amazon.com', ''),
('Amazon', 'amazonaws.com', ''),
('Amber Fusion Hub', 'amberfusionhub.com', ''),
('Amber Fusion Network', 'amberfusionnetwork.com', ''),
('American Concrete', 'americanconcreteonline.com', ''),
('AmiDi Group', 'amidigroup.com', ''),
('Ammax Bio', 'ammaxbio.com', ''),
('AmorePacific', 'apgroup.com/int/en', ''),
('Andreessen Horowitz', 'a16z.com', ''),
('Andrews Mixers', 'andrewsmixers.com', ''),
('Another Food Co.', 'anotherfood.co', 'Low'),
('Ansarada', 'ansarada.com', ''),
('Antares Ventures', 'antares.ventures', ''),
('Antarka', 'antarka.bio', 'Medium'),
('Anthology', 'anthology.net', 'Low'),
('Anthropic', 'email.anthropic.com', ''),
('Anthropic', 'mail.anthropic.com', ''),
('Antinori Napa Valley', 'antinorinapavalley.com', ''),
('Apellis', 'apellis.com', ''),
('Apex Group', 'apexgroup.com', ''),
('Apex Invest', 'events.apexinvest.io', ''),
('Apex Invest', 'apexinvest.io', ''),
('Apeximmune', 'apeximmune.com', 'Low'),
('APL Ventures', 'apl.ventures', ''),
('Apple', 'icloud.com', ''),
('Apple', 'me.com', ''),
('Apple', 'mac.com', ''),
('Applied Ventures', 'appliedventures.com', ''),
('Aquila Clouds', 'aquilaclouds.com', ''),
('Aragen', 'aragen.com', ''),
('Arc Group', 'arc-group.com', ''),
('Arcasa Science', 'arcascience.ai', ''),
('Arculus Solutions', 'arculus-solutions.com', ''),
('Arecor', 'arecor.com', ''),
('Aries Systems Corporation', 'aries.com', ''),
('Arlan Biotech', 'arlanbiotech.com', 'Low'),
('Arnold & Porter', 'arnoldporter.com', ''),
('Arovia', 'arovia.com', ''),
('ARPA-H', 'arpa-h.gov', ''),
('Arrakis', 'arrakis.bio', 'Medium'),
('Arrow Biome', 'arrowbiome.com', ''),
('Ascend', 'ascend.vc', ''),
('Ascendant Bio Capital', 'ascendantbiocapital.com', ''),
('Ashton Global', 'ashtonglobal.com', ''),
('Asian Development Bank', 'adb.org', ''),
('AsimicA', 'asimica.com', 'Low'),
('AsparaGlue', 'asparaglue.com', 'Low'),
('AT&T Mail', 'emaildl.att-mail.com', ''),
('Atlas Venture', 'atlasventure.com', ''),
('AtmoSpark Technologies', 'atmosparkh2.com', ''),
('AtoMe', 'atome.us', ''),
('Audio Vitality', 'audiovitality.com', ''),
('August GP', 'augustgp.com', ''),
('Avant Guard', 'avantguardinc.com', ''),
('Avenue Biosciences', 'avenuebiosciences.com', ''),
('Avisa Myko', 'avisamyko.com', 'Low'),
('Avnet', 'avnet.com', ''),
('Avnet', 'avnet.com', ''),
('Avstera Therapeutics Inc.', 'avstera.com', ''),
('Axon Energy', 'axonenergy.ai', ''),
('Ayrton Energy', 'ayrtonenergy.com', ''),
('Babson College', 'babson.edu', ''),
('Bain & Company', 'bain.com', ''),
('BANIQL', 'baniql.com', 'High'),
('Banyan', 'groupbanyan.com', ''),
('Banyan Tree', 'stay.banyantree.com', ''),
('Banyan Tree', 'banyantree.com', ''),
('BASF', 'basf.com', ''),
('Basketball Association of Singapore', 'nbas.org.sg', ''),
('Bay Area Times', 'bayareatimes.com', ''),
('BCA', 'bca.gov.sg', ''),
('bcengi', 'ping.bcengi.email', ''),
('Beehiiv', 'mail.beehiiv.com', ''),
('Beiley Biofund', 'beileybiofund.com/pages/english', ''),
('Bellcast Partners', 'bellcastpartners.com', ''),
('Beyond Bridge', 'beyondbridge.co', ''),
('BIA', 'bia.com.bn', ''),
('Big Blue', 'bigbluetec.com', 'Medium'),
('Big Blue Tech', 'bigbluetec.com', ''),
('Big Blue Technologies', 'bigbluetec.com', ''),
('Big Idea Ventures', 'bigideaventures.com', ''),
('Biip', 'biip-dcc.org', ''),
('Bikaner Advisors', 'bikaneradvisors.com', ''),
('Bio', 'bio.org', ''),
('Bio Technology Service', 'btsh2.com', 'Medium'),
('BioBoost', 'bioboostsynbio.com', ''),
('BioBreak', 'biobreak.org', ''),
('BioCentury', 'biocentury.com', ''),
('biocom', 'biocom.org', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));