WITH updates(name, domain, priority) AS (VALUES
('Sumitomo Chemical', 'sumichem.com', ''),
('Sumitomo Trust', 'sumithk.com', ''),
('Summit Agricultural Partners', 'summit-ap.com', ''),
('Summit Automotive Partners', 'summit-ap.com', ''),
('Sun Metalon', 'sunmetalon.com', ''),
('Sunbird Bio', 'sunbirdbio.com', ''),
('Suncelmo', 'suncelmo.co.jp', ''),
('Sungreen H2', 'sungreenh2.com', ''),
('Super Carb', 'supercarb.tech', 'Medium'),
('Supercool Earth', 'supercool-earth.com', 'Low'),
('Superhuman Ventures', 'superhumanventurescorp.com', ''),
('supermomos', 'supermomos.com', ''),
('Supervision Partners', 'supervisionpartners.com', ''),
('Swiss Biotech', 'swissbiotech.org', ''),
('Switch.', 'switchsg.org', ''),
('Swoogo', 'swoogo.com', ''),
('SWS Investments', 'sws-inv.com', ''),
('SXD', 'sxd-ai.com', ''),
('Syenta', 'syenta.com', ''),
('Synanthra', 'synanthra.com', 'Medium'),
('Synconize', 'umail.synconize.cn', ''),
('Synovance', 'synovance.com/en', 'Low'),
('Tabor Capital', 'taborcapital.com', ''),
('Tabsquare', 'tabsquare.com', ''),
('Tactiq', 'tactiq.io', ''),
('Tahaluf', 'event.tahaluf.com', ''),
('Tahaluf Al Emarat Technical Solutions', 'e.tahaluf.com', ''),
('Taiga', 'taigakorea.com', ''),
('Tanaka Manufacturing Co.', 'ml.tanaka.co.jp', ''),
('Targtex', 'targtex.com', ''),
('Taros Chemicals AG', 'taros.de', ''),
('TCV', 'tcv.com', ''),
('TDI Sustainability', 'tdi-sustainability.com', ''),
('TEAM LEWIS', 'teamlewis.com', ''),
('Tech Week', 'tech-week.com', ''),
('Tech40', 'tech40.net', ''),
('Teema Group', 'teemagroup.com', ''),
('Temasek', 'temasek.com.sg', ''),
('Temasek', 'temasek.com.sg', ''),
('Temasek Foundation', 'temasekfoundation.org.sg', ''),
('Temasek Foundation', 'temasekfoundation.org.sg', ''),
('TeOra Bio', 'teoralife.com', 'High'),
('Terasaki Institute for Biomedical Innovation', 'terasaki.org', ''),
('Terra Oleo', 'terraoleo.com', 'High'),
('Terrain Capital', 'terraincapital.com', ''),
('Tersa', 'tersa.earth', 'Low'),
('Thai Oil Public Company Limited', 'thaioilgroup.com', ''),
('The Biz Dev Wizard', 'thebizdevwizard.com', ''),
('The company associated with the domain dwtc.com is Dubai World Trade Centre.', 'dwtc.com', ''),
('The company name is Brevo.', '9508868.brevosend.com', ''),
('The company''s name is Dropbox.', 'em-s.dropbox.com', ''),
('The Dev Wizard', 'thedevwizard.com', ''),
('The Empire', 'theempirebrunei.com', ''),
('The name of the company is Education Digital Bureau.', 'email.edb.gov.sg', ''),
('The Real Care', 'thereal.care', ''),
('The Regal Team', 'theregalteam.com', ''),
('The Rocket Science Group', '38665077.mailchimpapp.com', ''),
('The Work Boulevard', 'theworkboulevard.com', ''),
('Thea Energy', 'thea.energy', 'Low'),
('Thea Energy', 'thea.energy', ''),
('ThermoBionics', '', 'Low'),
('TheWell Bioscience', '', 'Low'),
('THINK BIOSCIENCE', '', 'Low'),
('Tiamat Sciences', 'tiamat-sciences.com', ''),
('tideview', 'tideviewfo.com', ''),
('Tierra Biosciences, Inc.', '', 'Low'),
('Tikva Allocell', 'tikvaallocell.com', ''),
('TippingPoint Biosciences', 'tippingpointbiosciences.com', 'Medium'),
('Toast', 'toast-restaurants.com', ''),
('Tock', 'exploretock.com', ''),
('Top Harvest Capital', 'topharvestcap.com', ''),
('Top Tier Impact', 'toptierimpact.com', ''),
('TOP Ventures (Thai Oil)', 'topventures.co.th', ''),
('Toronto Metropolitan University', 'cloudmail.torontomu.ca', ''),
('Toronto Metropolitan University', 'torontomu.ca', ''),
('TPC House', 'tpchouse.com', ''),
('Trail Bio', 'trailbio.com', ''),
('Transition Biomining', 'transition.bio', 'Medium'),
('TransLink', 'translink.kr', ''),
('Translink Capital', 'trankslinkcapital.com', ''),
('Trend Micro', 'tmes.trendmicro.eu', ''),
('Tripleseat', 'tripleseat.com', ''),
('Tripleseat', 'discussions.tripleseat.com', ''),
('Trirec', 'trirecpl.com', ''),
('Trisail Medical', 'trisailmedical.com', ''),
('Truffle', 'truffle.com', ''),
('Truist', 'truist.com', ''),
('TrustYou', 'trustyou.com', ''),
('TTV Capital', 'ttv.vc', ''),
('Turk Telekom', 'turktelekom.com.tr', ''),
('Type6 Therapeutics', 'type6tx.com', 'Medium'),
('UCEA', 'ucea.pt', ''),
('UDN Group', 'udngroup.com', ''),
('Uluu', 'uluu.com.au', ''),
('U-Member', 'u-member.com.cn', ''),
('UniBio', 'unibaio.com', ''),
('United Airlines', 'united.com', ''),
('Univ UBS', 'univ-ubs.fr', ''),
('Universal Materials Incubator (UMI)', 'umi.co.jp/en', ''),
('University of California, Berkeley', 'berkeley.edu', ''),
('University of California, San Francisco', 'ucsf.edu', ''),
('University of Colorado Anschutz Medical Campus', 'cuanschutz.edu', ''),
('University of Texas at Austin', 'che.utexas.edu', ''),
('University of Toronto', 'utoronto.ca', ''),
('UNKNOWN', 'justinscholz.de', ''),
('Upcyclex', 'upcyclex.tech', ''),
('Valence Capital', 'valuencecap.com', ''),
('Valley Research Park', 'valleyresearchpark.com', ''),
('Vanderbilt University', 'vanderbilt.edu', ''),
('Vector AIS', 'vectorais.com', ''),
('Venture News', 'news.vntr.vc', ''),
('ventureLAB', 'venturelab.ca', ''),
('Venuerific', 'venuerific.com', ''),
('Verde Nanomaterials', 'verdenano.com', ''),
('Verimmune', 'verimmune.com', ''),
('Vertex Holdings', 'vertexholdings.com', ''),
('Vibe Bio', 'vibebio.com', ''),
('Vickers Venture', 'vickersventure.com', ''),
('Vilota', 'vilota.ai', ''),
('Vimcal', 'mail.vimcal.com', ''),
('Vinteriors', 'vinteriorskc.com', ''),
('Viologen', '', 'Medium'),
('Virfold', 'virfold.io', ''),
('Viridis', 'viridisresearch.com', ''),
('Visible', 'visible.vc', ''),
('VisitCloud', 'visitcloud.com', ''),
('Vita Coco', 'vitacoco.com', ''),
('VMS Ireland', 'vmsireland.com', ''),
('Voodoo', '2021.somosvoodoo.com', ''),
('Voyager VC', 'voyagervc.com', ''),
('VqResearch', 'vqresearch.com', ''),
('Vridhi Home Finance', 'vridhihomefinance.com', ''),
('Walter and Eliza Hall Institute of Medical Research', 'wehi.edu.au', ''),
('Washington University in St. Louis', 'wustl.edu', ''),
('Wasna', 'wasna.co', 'Low'),
('Wave', 'waveapps.com', ''),
('Wayfinder Bio', 'wayfinderbio.com', ''),
('Wayfinder Bio', 'wayfinderbio.com', 'Medium'),
('Wealthing', 'wealthing.vc', ''),
('Web Summit', 'websummit.com', ''),
('Weebly', 'promote.weebly.com', ''),
('Weehur', 'weehur.com.sg', ''),
('Weeloy', 'weeloy.com', ''),
('Weizmann Institute of Science', 'weizmann.ac.il', ''),
('Westport Alpha', 'westportalpha.com', ''),
('Westwood Aerogel', 'westwoodaerogel.com', ''),
('Weybridge Partners', 'weybridge.partners', ''),
('WGroup', 'wgrou.com', ''),
('wheresyoured', 'wheresyoured.at', ''),
('Whitworth University', 'whitworth.edu', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));