WITH updates(name, domain, priority) AS (VALUES
('DC Partners', 'dcpartners.capital', ''),
('DCM Ventures', 'dcm.com', ''),
('D-CRBN', 'd-crbn.com', ''),
('De Novo Dairy', 'denovodairy.com', ''),
('Decile Hub', 'decilehubmail.com', ''),
('Decycle Bio', 'decycle.bio', ''),
('DeepSeq.AI', 'deepseq.ai', ''),
('Deerfield', 'deerfield.com', ''),
('Deimpact', 'deimpact.org', ''),
('Del Morgan & Co.', 'delmorganco.com', ''),
('Deloitte', 'deloitte.com', ''),
('Deloitte', 'deloitte.com', ''),
('Demy Colton', 'demy-colton.com', ''),
('Denka', 'denka.co.jp', ''),
('DEXMAT', 'dexmat.com', 'Medium'),
('Diesel Care', 'dieselcare.net', ''),
('Dify', 'dify.ai', ''),
('Dimov Tax', 'dimovtax.com', ''),
('DLF Hospitality', 'dlfhospitality.in', ''),
('DLG Law', 'dlglaw.co.kr', ''),
('DocuSign', 'docusign.net', ''),
('Donald Capital', 'donaldcapital-ny.com', ''),
('Dong-a Pharma', 'dapharm.com/en', ''),
('Doon Insights', 'dooninsights.com', ''),
('Draper University', 'draperuniversity.com', ''),
('Driven Plastics', 'drivenplastics.com', ''),
('Drooms', 'drooms.com', ''),
('Dropbox', 'docsend.com', ''),
('Drover Ventures', 'droverventures.com', ''),
('Duke University', 'duke.edu', ''),
('Dunn Innovations', 'dunninc.net', ''),
('dYdX Foundation', 'dydx.foundation', ''),
('Dynam Capital', 'dynamcapital.com', ''),
('E Evaluate', 'e.evaluate.com', ''),
('Earth Protex', 'earthprotex.com', ''),
('EBD Group', 'ebdgroup.com', ''),
('Eclipse Ventures', 'eclipse.vc', ''),
('Ecliptic Capital', 'eclipticcapital.com', ''),
('Eco-Business', 'eco-business.com', ''),
('Ecopha', 'ecopha.com', ''),
('Ecotech Capital', 'ecotechcap.com', ''),
('EDB (Economic Development Board)', 'edb.gov.sg', ''),
('EDBI', 'edbi.com', ''),
('Edinburgh Development Board', 'mail.edb.gov.sg', ''),
('EDM Enterprise', 'edm.enterprisesg.com.sg', ''),
('EFCAN', 'efcan.com.br', ''),
('Eff Consulting', 'effconsulting.com', ''),
('Effem', 'effem.com', ''),
('efishient', 'efishient.co.il', ''),
('Eigen', 'eigen.digital', ''),
('Elavon', 'elavon.com', ''),
('Electroflow Technologies', 'eflowtech.com', 'High'),
('Elev8 Venture Partners', 'elev8.vc', ''),
('Elevate Talent', 'elevatetaptalent.com', ''),
('Eli Lilly', 'lilly.com', ''),
('Elpis Biopharmaceuticals', 'elpisbiopharm.com', ''),
('elucidata', 'elucidata.io', ''),
('Elysia Bio', 'elysiabio.com', 'Medium'),
('eMart', 'emart.com', ''),
('Enavle', 'enavle.com', ''),
('Energy Impact Partners', 'eip.com', ''),
('Enervenue', 'enervenue.com', ''),
('Enmore', 'enmore.com', ''),
('Enmore Bio', 'global.enmorebio.com', ''),
('Enterprise Singapore', 'enterprisesg.gov.sg', ''),
('Envoy', 'envoy.com', ''),
('Eolic Wall', 'eolicwall.com', ''),
('Episteme Diagnostics', 'epistemedx.com', ''),
('eReceipt', 'ereceipt.usps.gov', ''),
('Eric Ripert', 'ericripert.com', ''),
('escoaster', 'escoaster.com', ''),
('Essentia', 'essentia.vc', ''),
('Essex', 'essex.com.sg', ''),
('EUC International', 'kg.euci.com', ''),
('EUC Solutions', 'ms.euci.com', ''),
('Eurasanté', 'eurasante.com', ''),
('Europcar', 'europcar.com', ''),
('Eva', 'evacorp.ai', ''),
('Eva Garland Consulting', 'evagarland.com', ''),
('Evaluate', 'info.evaluate.com', ''),
('Eventbrite', 'order.eventbrite.com', ''),
('Eventbrite', 'event.eventbrite.com', ''),
('Eventbrite', 'plans.eventbrite.com', ''),
('Eventbrite', 'campaign.eventbrite.com', ''),
('Eventbrite', 'email.eventbrite.com', ''),
('EventsHQ', 'exl.eventshq.com', ''),
('Evercloak', 'evercloak.com', ''),
('Evio', 'evio.asia', ''),
('EvolvedBio', 'evolved.bio', 'Medium'),
('EVV Portfolio', 'evvportfolio.com', ''),
('Exodys Energy', 'exodysenergy.com', 'Low'),
('Explori', 'mailer.explori.com', ''),
('Expostandzone', 'expostandzone.com', ''),
('Eztia', 'eztiahealth.com', ''),
('Fairmont Hotels & Resorts', 'fairmont.com', ''),
('Fathom', 'fathom.video', ''),
('FCC Singapore', 'fccsingapore.com', ''),
('FedEx', 'fedex.com', ''),
('Feon Energy', 'feonenergy.com', ''),
('Fermionic', 'fermionic.com', ''),
('Ferrum Technologies', 'ferrumtech.com', ''),
('Feynman Labs', 'feynmanlabs.sg', 'Medium'),
('FG Bradley''s', 'fgbradleys.com', ''),
('FibroCort Therapeutics', 'fibrocortherapeutics.com', ''),
('Field Ventures', 'fieldvc.com', ''),
('Fifth Innovation Oy', 'fifthinnovation.fi', ''),
('Fifth Wave Metals', 'fifthwavemetals.com', 'Medium'),
('Fillout', 'fillout.com', ''),
('FinCompliance', 'fincompliance.io', ''),
('Finsmes', 'finsmes.com', ''),
('Fireflies', 'fireflies.ai', ''),
('Firefly', 'firefly.com.my', ''),
('Fireflyz', 'fireflyz.com.my', ''),
('Flagship Pioneering', 'flagshippioneering.com', ''),
('Florida State University', 'chem.fsu.edu', ''),
('FlueVault', 'fluevault.com', 'Medium'),
('Fluxo', 'fluxomade.com', 'Low'),
('Fly Alliance', 'flyalliance.com', ''),
('Foley Hoag', 'foleyhoagllp.com', ''),
('Foley Hoag', 'foleyhoag.com', ''),
('Foray Bioscience', 'foraybio.com', ''),
('Force Family Office', 'forcefamilyoffice.com', ''),
('Forever Analytical', 'foreveranalytical.com', ''),
('Formidium', 'formidium.com', ''),
('Forta', 'forta.bio', ''),
('founders village', 'foundersvillage.co', ''),
('Freeflow', 'freeflow.io', ''),
('Frontier Bio', 'frontierbio.com', 'Medium'),
('Fuel Well Saver', 'fuelwellsaver.info', ''),
('Fujitsu', 'fujitsu.com', ''),
('Fuzionaire', 'fuzionaire.com', ''),
('G2', 'campaigns.g2.com', ''),
('Gaia Lens', 'gaia-lens.com', ''),
('galaxyuniverse', 'galaxyuniverse.ai', ''),
('Gardens by the Bay', 'gardensbythebay.com.sg', ''),
('Gardin', 'gardin.ag', 'Medium'),
('GCV Life', 'gcvlife.in', ''),
('GecKo Materials', 'geckomaterials.com', ''),
('GelSana', 'gelsanatherapeutics.com', ''),
('Gemseki', 'gemseki.com', ''),
('Gencat', 'gencat.cat', ''),
('General Catalyst', 'generalcatalyst.com', ''),
('General Inception', 'generalinception.com', ''),
('General Motors', 'gm.com', ''),
('General Sense', 'generalsense.com', ''),
('generalcontrol', 'generalcontrol.inc', ''),
('GENERIC', 'outlook.com', ''),
('geneva ppli', 'geneva-ppli.com', ''),
('Genome', 'genomecom.co.kr', ''),
('Genopole', 'genopole.fr', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));