WITH updates(name, domain, priority) AS (VALUES
('GenZero', 'genzero.co', ''),
('GEVME', 'gevme.com', ''),
('GGV Capital', 'ggvc.com', ''),
('Ghadiscovery', 'email.ghadiscovery.com', ''),
('Gham', 'gham.com.sg', ''),
('GHL', 'e-ghl.com', ''),
('Ghost Management Group', 'ghost.wheresyoured.at', ''),
('Gilbert Home Comfort', 'gilberthomecomfort.com', ''),
('Giraffe Bio', 'giraffe-bio.com', 'Medium'),
('Giraffe Biosciences', 'giraffe-bio.com', ''),
('GlobalData', 'globaldata.com', ''),
('GoDaddy', 'godaddy.com', ''),
('Golden Hill Asset Management (GHAM)', 'gham.com.sg', ''),
('Gong', 'gong.io', ''),
('Goodwater Capital', 'goodwatercap.com', ''),
('Goodwood', 'goodwood.sg', ''),
('Google', 'gmail.com', ''),
('Google', 'group.calendar.google.com', ''),
('Google', 'google.com', ''),
('Google', 'accounts.google.com', ''),
('Google', 'googlemail.com', ''),
('GovDelivery', 'public.govdelivery.com', ''),
('Grain', 'grain.com.sg', ''),
('Granite Asia', 'graniteasia.com', ''),
('granola', 'mail.granola.so', ''),
('Greater Giving', 'online.greatergiving.com', ''),
('Green Willow', 'greenwillow.com.sg', ''),
('Greenitio', '', 'Medium'),
('Greenvelope', 'invites.greenvelope.com', ''),
('Greenvelope', 'greenvelope.com', ''),
('Grove Harbour Marina', 'groveharbourmarina.com', ''),
('GS Energy', 'gsenergy.co.kr', ''),
('GS Futures', 'gsfutures.vc', ''),
('GSK', 'gsk.com', ''),
('Gurryshark', 'gurryshark.com', ''),
('Halborn', 'halborn.com', ''),
('Hana Financial', 'hanafn.com', ''),
('Hand of God Wines', 'handofgodwines.ccsend.com', ''),
('Hanwha', 'hanwha.com', ''),
('Hartford Advisors', 'hartfordadvisorskyc.org', ''),
('Hartford Human Intelligence', 'hartford-humanintel.com', ''),
('Hazaiya', 'hazaiya.co.jp', ''),
('Heat Inverse', '', 'Low'),
('Helms Briscoe', 'helmsbriscoe.com', ''),
('Hemispherian', 'hemispherian.com', ''),
('Henkel', 'henkel.com', ''),
('Heritas Capital Management', 'heritas.com.sg', ''),
('Hexemb', 'hexemb.io', ''),
('High Tech', 'hight-tech.com', ''),
('Hight Tech', 'hight-tech.com', ''),
('HiT Nano', 'hitnanoinc.com', 'Medium'),
('Hiven', 'hiven.com.sg', ''),
('Holistic Solutions', 'hol.sg', ''),
('Honda Innovations', 'hondainnovations.com', ''),
('Horizons Ventures', 'horizons.com.hk', ''),
('Hospitality Headline', 'hospitalityheadline.com', ''),
('HubSpot', 'hubspot.com', ''),
('HubSpot', 'notifications.hubspot.com', ''),
('HubSpot', 'hubspotfree.na2.hs-send.com', ''),
('HubSpot', 'hubspotstarter.hs-send.com', ''),
('hubspot', 'hubspotstarter.na3.hs-send.com', ''),
('HubSpot', 'hubspotfree.hs-send.com', ''),
('Hummingbird Ventures', 'hummigbird.vc', ''),
('Hyatt', 'em.hyatt.com', ''),
('Hyatt', 'hyatt.com', ''),
('Hyatt', 'loyalty.hyatt.com', ''),
('Hyatt Hotels Corporation', 'm1.hpe-esp.hyatt.com', ''),
('HyperForge', 'hyperforge.co', ''),
('HyWatts', 'hywatts.com', 'Low'),
('IB Hospitality', 'ibhospitality.com', ''),
('IBK Korea', 'global.ibk.co.kr', ''),
('iConnections', 'iconnections.io', ''),
('Ideals', 'idealsvdr.com', ''),
('ignite_inv', 'ignite-inv.com', ''),
('IISolutions', 'iisolutions.ch', ''),
('Iktos', 'iktos.com', ''),
('Iland', 'iland6.com', ''),
('Ildong Pharma', 'ildong.com', ''),
('Illumina', 'illumina.cpa', ''),
('Illumina CPA', 'illuminacpa.clientportal.com', ''),
('Illumina Ventures', 'illuminaventures.com', ''),
('Imagina', 'imagina.com', ''),
('Imagina', 'imagina.io', ''),
('Immin Investment', 'imminvestment.com', ''),
('Immuno Biome', '', 'Low'),
('Immuse', 'immusetx.com', ''),
('IMNEWRUN', 'imnewrun.com', 'Low'),
('Impact Cooling', 'impactcooling.com', 'Medium'),
('Impact Cooling', 'impact-cooling.com', 'Medium'),
('Impact Cooling', 'impactcooling.com', ''),
('Impact Week', 'impactweek.com', ''),
('ImpriMedicine', 'imprimedicine.com', ''),
('Imre', 'imre.a-star.edu.sg', ''),
('Industrial Microbes', 'imicrobes.com', 'Medium'),
('Informa', 'informa.com', ''),
('Informa Connect', 'email.informaconnect.com', ''),
('Informa Connect', 'informaconnect.com', ''),
('ingo', 'ingo.me', ''),
('Inline', 'inline.tw', ''),
('INNOPOWER', 'innopower.com', ''),
('Innotek', 'innotek.lu', ''),
('Innovate360', 'innovate360.sg', ''),
('INSEAD', 'insead.edu', ''),
('Intactis', 'intactis.bio', 'Medium'),
('intelligence', 'intelligence.com', ''),
('Interactive Brokers', 'interactivebrokers.com', ''),
('Interactive Brokers', 'email.interactivebrokers.com', ''),
('Interactive Brokers', 'interactivebrokers.com.sg', ''),
('Interface Biosciences', 'interface.bio', ''),
('Intevity', 'intevity.com', ''),
('Intuit', 'em1.turbotax.intuit.com', ''),
('Intuit', 'intuit.com', ''),
('InventWood', 'inventwood.com', ''),
('Invest Seoul', 'investseoul.org', ''),
('Investible', 'investible.com', ''),
('Involved Events', 'involvedevents.com', ''),
('IOI Group', 'ioigroup.com', ''),
('Ionless', 'ionless.com', ''),
('Ionless Corporation', 'ionless.com', 'Medium'),
('iqt', 'iqt.org', ''),
('ISA Industrial', 'isaindustrial.com', ''),
('it-farm', 'it-farm.vc', ''),
('Ivim Technology', 'ivimtech.com', ''),
('Jack Richards Insurance', 'jackrichardsinsurance.com', ''),
('Jamie', 'hey.meetjamie.ai', ''),
('Jelawang Capital', 'jelawangcapital.com', ''),
('Jellatech', 'jellatech.com', 'Low'),
('JESUIS ELLE', 'jesuiselle.info', ''),
('JETRO', 'jetro.go.jp', ''),
('JK Advisory', 'jkadvisory.llc', ''),
('JLL', 'jll.com', ''),
('Johnson & Johnson', 'its.jnj.com', ''),
('Johnson & Johnson Innovation', 'jnjinnovation.com', ''),
('Jotform', 'jotform.com', ''),
('JPMorgan', 'jpmorgan.com', ''),
('JR Preston', 'jrpreston.com', ''),
('JTB Communication Design', 'jtbcom.co.jp', ''),
('JTC', 'jtc.gov.sg', ''),
('Jubilant Biosys', 'jubilantbiosys.com', ''),
('Jublia', 'jublia.co', ''),
('Just Private Tour', 'justprivatetour.com', ''),
('K2 Bio Capital', 'k2biocapital.vc', ''),
('Kaigene, Inc', 'kaigene.com', ''),
('Kajabi', 'y.kajabimail.net', ''),
('Karma', 'karmak.com', ''),
('Katapult', 'katapult.vc', ''),
('Keio MCC', 'keiomcc.com', ''),
('Kemwell Pharma', 'kemwellpharma.com', ''),
('Kindred Ventures', 'kindredventures.com', ''),
('Kinesiometrics', 'kinesiometrics.org', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));