WITH updates(name, domain, priority) AS (VALUES
('Redace Bio', 'redacebio.com', ''),
('REEgen', 'reegen.tech', ''),
('REEMAG LLC', 'reemag.net', ''),
('RegenXBIO', 'regenxbio.com', ''),
('Relumino Therapeutics', 'reluminotx.com', 'Medium'),
('Remember', 'rememberapp.co.kr', ''),
('Reneubio', 'reneubio.com', 'Medium'),
('Repair Biotechnologies', 'repairbiotechnologies.com', ''),
('Replit', 'replit.com', ''),
('Replit', 'mail.replit.com', ''),
('Resend', 'notifications.resend.com', ''),
('Resend', 'updates.resend.com', ''),
('Retinovo', 'n/a', 'Low'),
('ReviveMed', 'revivemed.io', 'Low'),
('Revivo Biosystems', 'revivobio.com', ''),
('Revopsis', 'revopsis.com', ''),
('RevOpsis Therapeutics', 'revopsis.com', ''),
('Rialto Patrol', 'rialtopatrol.com', ''),
('Rigid Robotics', 'rigidrobotics.com', 'Low'),
('Riva Huerta Abogados', 'rivashuertaabogados.mx', ''),
('Riverbridge Capital', 'riverbridgecap.com', ''),
('Roca Water', 'rocawater.com', 'Medium'),
('Rocamaterials', 'rocamaterials.com', ''),
('Rockefeller University', 'rockefeller.edu', ''),
('Rockz Consulting', 'rockzconsulting.com', ''),
('Rooter Man', 'rooterman.com', ''),
('Rosalind', 'rosalinddx.com', ''),
('Royal Brunei Airlines', 'mail.flyroyalbrunei.com', ''),
('Royal Brunei Airlines', 'flyroyalbrunei.com', ''),
('Rushnu', 'rushnu.com', ''),
('RWTH Aachen', 'win.rwth-aachen.de', ''),
('S&P Global', 'spglobal.com', ''),
('S&P Global Packaging', 'spglobalpkg.com', ''),
('S2G Ventures', 's2gventures.com', ''),
('Sabancı ICT', 'sabancict.com', ''),
('Sage Boardroom', 'sageboardroom.com', ''),
('Sage Healthcare', 'sagehealthcare.com', ''),
('Sage3', 'sage3.com', ''),
('Samsung Ventures', 'samsungventure.co.kr/english/jsp/investment/sector.jsp', ''),
('San Francisco Court Appointed Special Advocates', 'volunteer.sfcasa.org', ''),
('San Francisco Wine Society', 'sanfranciscowinesociety.com', ''),
('Satin Corp', 'satincorp.com', ''),
('SATS', 'sats.com.sg', ''),
('SATS', 'sats.com.sg', ''),
('SCAI Therapeutics', 'scaitrx.com', ''),
('Scale Climate', 'scale-climate.org', ''),
('SCF Global', 'scf-global.com', ''),
('Schneider Electric', 'se.com', ''),
('Schneider Electric', 'se.com', ''),
('SciClone', 'sciclone.com', ''),
('Scindo', 'scindo.bio', 'High'),
('SciSemi', 'scisemi.com', ''),
('SciTech Development', 'scitechdevelopment.com', ''),
('Scoot', 'itinerary.flyscoot.com', ''),
('Scoot', 'notify.flyscoot.com', ''),
('SDTA', 'sdta.org.sg', ''),
('Sealed Air', 'sealedair.com', ''),
('Sedgwick Yard', 'sedgwickyard.com', ''),
('Seed Engineers', 'seedengineers.com', ''),
('SEEDS Capital', 'sggc.sg', ''),
('Seeds Capital', 'seedscapital.sg', ''),
('Seeds Capital', 'seedscapital.sg', ''),
('Seek Labs', 'seeklabs.com', ''),
('Seia Bio', 'seiabio.com', ''),
('Selta Square', '', 'Low'),
('SendFox', 'sendfoxmail.com', ''),
('Seoul National University', 'snu.ac.kr', ''),
('Seppure', 'seppure.com', 'Medium'),
('Sequoia Capital', 'sequoiacap.com', ''),
('Serenity Power', 'serenitypower.ca', 'Low'),
('Setherapeutics', 'setherapeutics.com', ''),
('SevenRooms', 'message.sevenrooms.com', ''),
('SevenRooms', 'email.sevenrooms.com', ''),
('SGGC', 'sggc.sg', ''),
('SGInnovate', 'sginnovate.com', ''),
('Sharp Corporation', 'sharp.co.jp', ''),
('Shimizu Corporation', 'shimz.co.jp', ''),
('Shinhan', 'shinhanvc.com/en', ''),
('Shinsegae / Emart', 'shinsegae.com', ''),
('SHMD', 'shmd.io', ''),
('Shopify', 'g.shopifyemail.com', ''),
('Shorewind Capital', 'shorewindcapital.com', ''),
('Sidley', 'sidley.com', ''),
('Sift Biosciences', 'siftbios.com', 'High'),
('Sightera Biosciences', 'sightera-biosciences.com', ''),
('silkit ltd.', 'silkit-bio.com', ''),
('Silverwood Capital', 'silverwoodcapital.com', ''),
('Silverwood Partners', 'silverwoodpartners.com', ''),
('Sime Darby Property', 'simedarbyproperty.com', ''),
('Sina', 'vip.sina.com', ''),
('Singapore Airlines', 'contact.singaporeair.com', ''),
('Singapore Airlines', 'singaporeair.com', ''),
('Singapore Airlines', 'email.singaporeair.com', ''),
('Singapore Airlines', 'flightinfo.singaporeair.com', ''),
('Singapore Airlines', 'singaporeair.com.sg', ''),
('Singapore Global Network', 'email.singaporeglobalnetwork.gov.sg', ''),
('Singapore Management University', 'smu.edu.sg', ''),
('Singapore Polytechnic', 'sp.edu.sg', ''),
('SingHealth', 'singhealth.com.sg', ''),
('Sixline Semi', 'sixlinesemi.com', ''),
('SixLine Semiconductor', 'sixlinesemi.com', 'Low'),
('SK', 'sk.com', ''),
('skeletonkey', 'skeletonkey.vc', ''),
('Skouria', 'skouria.com', ''),
('Sky VC', 'sky-vc.com', ''),
('SkyDeck', 'skydeck.vc', ''),
('SkyNano', 'skynanotechnologies.com', ''),
('Slack', 'slack.com', ''),
('Slack Mail', 'slack-mail.com', ''),
('snatchedventures', 'snatchedventures.com', ''),
('Snobol', 'snobol.com', ''),
('Social Innovation Summit', 'socialinnovationsummit.com', ''),
('Sofitel', 'sofitel.com', ''),
('Solar Steam', 'solarsteam.ca', ''),
('SOLETAIR POWER Oy', 'soletairpower.fi', ''),
('Sompo Japan Kii', 'sompo-japan-kii.com', ''),
('SOSV', 'sosv.com', ''),
('SOSV', 'sosv.com', ''),
('SOSV Matchups', 'emails.sosvmatchups.com', ''),
('Sound Financial Management', 'sfinvman.com', ''),
('South Sound Behavioral Hospital', 'southsoundbehavioralhospital.com', ''),
('Spacee', 'spacee.co.jp', ''),
('sparklabs', 'sparklabsgroup.com', ''),
('Spartha Medical', 'sparthamedical.eu', ''),
('Sparton Capital', 'sparton.capital', ''),
('Sparxell', 'sparxell.com', 'High'),
('Sparxell', 'sparxell.com', ''),
('Spectrum Impact', 'spectrum-impact.org', ''),
('Splash Tools', 'splash.tools', ''),
('SPMB', 'mg.spmb.com', ''),
('Springboard Enterprises', 'springboardenterprises.org', ''),
('Square', 'messaging.squareup.com', ''),
('Squarespace', 'mail.squarespace.com', ''),
('St Ambroise', 'st-ambroise.com', ''),
('Stage', 'stage.ac', ''),
('Stanford', 'stanford.edu', ''),
('Startup Career Advice', 'startupcareeradvice.com', ''),
('Startup Grind', 'startupgrind.com', ''),
('Station F', 'stationf.co', ''),
('Station F', 'stationf.co', ''),
('Station F', 'stationf.co', ''),
('Stein Law', 'steinlawllc.com', ''),
('Stellar Communications', 'stellarcommunications.net', ''),
('Stern', 'stern.nyu.edu', ''),
('Steve Hubbard Real Estate', 'stevehubbardrealestate.com', ''),
('STH Biotech', 'sth-biotech.com', 'Medium'),
('Stibee', 'send.stibee.com', ''),
('Stripe', 'stripe.com', ''),
('StrongBody', 'strongbody.ai', ''),
('Substack', 'substack.com', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));