WITH updates(name, domain, priority) AS (VALUES
('Neurovanda', 'neurovanda.com', ''),
('Nevastar', 'nevastar.com', ''),
('New Summit Capital Advisors', 'newsummitcapadvisors.com', ''),
('New West Genetics', 'newwestgenetics.com', ''),
('New York University', 'nyu.edu', ''),
('Newco Capital Group', 'newcocapitalgroup.com', ''),
('Newfound Materials', 'newfoundmaterials.com', ''),
('Next Generation', 'nextgeneration.com', ''),
('Next Legacy', 'nextlegacy.com', ''),
('NexTeam Consulting', 'nexteamconsulting.com', ''),
('NextGen Ventures', 'nxtgen.vc', ''),
('Nexus Events', 'nexusevents.io', ''),
('NH Ventures', 'nhvic.com', ''),
('Nicholas', 'nicholas-esq.com', ''),
('Nifty', 'nifty.com', ''),
('Nina Mansfield', 'ninamansfield.com', ''),
('NitroFix', 'nitro-fix.com', ''),
('NLC Health', 'nlc.health', ''),
('Nobula', 'nobula3d.com', ''),
('Nomura Greentech', 'nomuragreentech.com', ''),
('Nona Technologies', 'nona-technologies.com', ''),
('nor1upgrades', 'nor1upgrades.com', ''),
('Northwest Area Council', 'nwacouncil.org', ''),
('Notion', 'mail.notion.so', ''),
('Novel Farms', 'novelfarms.co', ''),
('Novel Farms', 'novelfarms.co', ''),
('Noviscient', 'noviscient.com', ''),
('Nurasa', 'nurasa.com', ''),
('NVIDIA', 'nvidia.com', ''),
('Oak Ridge National Laboratory', 'mailer.ornl.gov', ''),
('Oak Ridge National Laboratory', 'ornl.gov', ''),
('Oberlin College', 'oberlin.edu', ''),
('OCMS', 'ocms.bio', ''),
('Octave Capital', 'octavecapital.co', ''),
('Octopus Group', 'octopusgroup.com', ''),
('Octopus Ventures', 'octopusventures.com', ''),
('ODC Life Sciences', 'odclifesciences.com', ''),
('Oji Group', 'oji-gr.com', ''),
('Okosix', 'okosix.com', ''),
('Oleo Sustainable POS', 'oleospos.com/home', 'Medium'),
('OmicInsight', 'omicinsight.com', 'Medium'),
('Omnicell', 'omnicell.com', ''),
('Oncodea', 'oncodea.com', ''),
('OncoPatch', 'oncopatch.net', 'Medium'),
('Oncoshot', 'oncoshot.com', ''),
('One Touch Tech Solutions', 'app.onetouchtechsolutions.com', ''),
('OneValley', 'theonevalley.com', ''),
('OpenAI', 'tm.openai.com', ''),
('OpenAI', 'email.openai.com', ''),
('OpenAI', 'tm1.openai.com', ''),
('OpenTable', 'opentable.com', ''),
('Organics Rx', 'organicsrx.com', ''),
('Orissa International', 'orissa-international.com', ''),
('Orochem Technologies', 'orochem.com', ''),
('Orrick', 'orrick.com', ''),
('Orrick', 'orricklaw.com', ''),
('Orrick', 'orrick.com', ''),
('Orum Therapeutics', 'orumrx.com', ''),
('Osome', 'osome.com', ''),
('Osome', 'mail.osome.com', ''),
('Otoro Energy', 'otoroenergy.com', ''),
('Otter', 'otter.ai', ''),
('Otter Bio', 'otter-bio.com', ''),
('Outcomes Fund', 'outcomes.fund', ''),
('Pacific Alliance Ventures', 'pav.vc', ''),
('Package Plus', 'package-plus.com/en-home', ''),
('Pai QBD', 'pai-qbd.com', ''),
('Paradromics', 'paradromics.com', ''),
('Park Road Advisors', 'parkroadadvisors.com', ''),
('Park West', 'parkwestllc.com', ''),
('Partnering', 'hellopartnering.com', ''),
('PartneringONE', 'partneringone.com', ''),
('Pathomics Health', 'pathomicshealth.com', ''),
('Pavilion Capital Ventures', 'pav.vc', ''),
('PCCW Solutions', 'netvigator.com', ''),
('PD1', 'pd1.onpdr.com', ''),
('Pear VC', 'pear.vc', ''),
('Pelecia', 'pelecia.com.br', ''),
('Perplexity', 'mail.perplexity.ai', ''),
('Pharmaventures', 'pharmaventures.com', ''),
('PheedLoop', 'pheedloop.com', ''),
('Philanthropy Asia Alliance', 'philanthropyasiaalliance.org', ''),
('Photosynthetic', 'photosynthetic.nl', 'Medium'),
('Phytogenesis', 'phytogenesis.com', 'Medium'),
('Phytolon', 'phytolon.com', ''),
('Piedmont Copy', 'piedmontcopy.com', ''),
('Pienaar', 'thepienaar.com', ''),
('Pillar VC', 'pillar.vc', ''),
('PillSafe', 'startpillsafe.com', ''),
('Pine Tree', 'pinetree.sg', ''),
('PineTree', 'pinetree.sg', ''),
('Pipestone Partners', 'pipestonepartners.com', ''),
('PitchBook', 'news.pitchbook.com', ''),
('PitchBook Data', 'pitchbook.com', ''),
('Planet Carbon', 'planetcarbon.earth', ''),
('Plantik Biosciences', 'plantik.bio', 'Medium'),
('Plasma BioWorks', 'plasmabioworks.com', ''),
('Plasmonica', 'plasmonica.com', 'Medium'),
('Plasmonica', 'plasmonica.com', ''),
('Pleno', 'plenoinc.com', ''),
('PlusAI', 'plusai.com', ''),
('PNPTC', 'pnptc.com', ''),
('Popl', 'getpopl.com', ''),
('POSCO', 'posco-inc.com', ''),
('Power Down Semiconductor', 'powerdownsemi.com', ''),
('Poze Caf', 'pozescaf.com', ''),
('Precise Health', 'precisehealth.io', ''),
('PredxBio', '', 'Medium'),
('Prelude Ventures', 'preludeventures.com', ''),
('Premium Technics', 'premiumtechnics.be', ''),
('PressWhot', 'presswhot.com', ''),
('Prestel and Partner', 'prestelandpartner.com', ''),
('Prestige Bio.', 'prestigebio.com', ''),
('Presto Labs', 'prestolabs.io', ''),
('Prime Outlier', 'primeoutlier.com', ''),
('PrismBio', 'prismbioinc.com', 'Medium'),
('ProAgni', 'proagni.com', ''),
('Prostate Cancer Foundation', 'pcf.org', ''),
('Protai', 'protai.bio', ''),
('Protheragen', 'protheragen.us', ''),
('Protheragen', 'protheragen.com', ''),
('Proton', 'proton.me', ''),
('Proton AG', 'pm.me', ''),
('PT Medicines', 'ptmedicines.com', ''),
('PTT ExpresSo', 'expresso.pttplc.com', ''),
('Purteq', 'purtecteam.com', ''),
('Putnam Insights', 'putnaminsights.com', ''),
('PVM', 'pvm.global', ''),
('Q Email Server', 'qemailserver.com', ''),
('QarboTech', 'qarbotech.com', ''),
('QDX', 'qdx.co', 'Medium'),
('Qualtrics', 'qualtrics-survey.com', ''),
('Quantivly', 'quantivly.com', ''),
('Quantum Leaps', 'qxl.jp', ''),
('QuestNow', 'questnow.net', ''),
('Quinn Emanuel', 'quinnemanuel.com', ''),
('Quinn Emanuel', 'quinnemanuel.com', ''),
('Quorum Bio', 'quorum-bio.com', ''),
('Qureator', 'qureator.com', ''),
('Qymune', 'qymune.com', ''),
('Radyus Research', 'radyusresearch.com', ''),
('Raidium', 'raidium.eu', ''),
('Raise Global', 'raiseglobal.co', ''),
('Rare Flora', 'rareflora.bio', ''),
('Rare Terra', 'rare-terra.com', ''),
('RB Growth Equity', 'rbgrowthequity.info', ''),
('RE:lumino', 'reluminotx.com', ''),
('Reactosome', 'reactosome.com', ''),
('Reactosome', 'reactosome.com', 'High'),
('Read AI', 'e.read.ai', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));