WITH updates(name, domain, priority) AS (VALUES
('Kitox', 'kitox.re.kr', ''),
('Knobbe', 'knobbe.com', ''),
('Koceco', 'koceco.co.kr', ''),
('Korea Bridging', 'koreabridging.com', ''),
('Korea University', 'korea.ac.kr', ''),
('Korea Venture Investment Corp.', 'kvic.or.kr', ''),
('Korean Air', 'koreanair.com', ''),
('Kortuc', 'kortuc.com', ''),
('KPBMA', 'kpbma.or.kr', ''),
('KROSSLINKER', 'krosslinker.com', ''),
('KSI Link', 'ksilink.com', ''),
('Kvicus', 'kvicus.com', ''),
('L.E.K. Insights', 'lekinsights.com', ''),
('L’Oreal', 'loreal.com', ''),
('LabStart', 'labstart.co', ''),
('Landmark Ventures', 'landmarkventures.com', ''),
('LawPay', 'appmailer.lawpay.com', ''),
('LCO', 'lco.legal', ''),
('Leap Ai', 'leap-ai.com', ''),
('Lee & Lee', 'leenlee.com.sg', ''),
('Lee Yin', 'leeyin.com.sg', ''),
('Lesaffre', 'lesaffre.com', ''),
('Leverage', 'leveragen.com', ''),
('LexisNexis Risk Solutions', 'lexisnexisrisk.com', ''),
('LG', 'lg.com', ''),
('LG Chem', 'lgchem.com/main/index', ''),
('LG Tech Ventures', 'lgtechventures.com', ''),
('Life Science Nation', 'lifesciencenation.com', ''),
('Lifespan Vision', 'lifespanvision.com', ''),
('Light Tech', 'light-tech.io', ''),
('Ligo Partners', 'ligopartners.com', ''),
('Limitless', 'limitless.network', ''),
('Lingotto Innovation Strategy', 'lingotto.com', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('Local Bounti', 'localbounti.com', ''),
('Longitude Capital', 'longitudecapital.com', ''),
('Loxegen', 'loxegen.net', ''),
('LSX Leaders', 'lsxleaders.com', ''),
('Lu. ma', 'lu.ma', ''),
('Luma', 'luma.com', ''),
('Luma Health', 'user.luma-mail.com', ''),
('Luma Mail', 'calendar.luma-mail.com', ''),
('Luma Mail', 'luma-mail.com', ''),
('Luminos Capital', 'luminoscapital.com', ''),
('Lunit', 'lunit.io', ''),
('Lux Capital', 'luxcapital.com', ''),
('Magnimind Academy', 'magnimindacademy.com', ''),
('Magnotherm Solutions', 'magnotherm.com', ''),
('Mahipono', 'mahipono.com', ''),
('Maia Farms', 'maiafarms.ca', ''),
('Mailchimp', '11114499.mailchimpapp.com', ''),
('Mailva', 'mailva.evite.com', ''),
('Make', 'us1.make.com', ''),
('Malaysia Airlines', 'malaysiaairlines.com', ''),
('Malaysian Research Accelerator for Technology and Innovation', 'mranti.my', ''),
('Mangusta Capital', 'mangustacap.com', ''),
('Mara Malabs', 'maramalabs.com', ''),
('Marama Labs', 'techbio', 'Medium'),
('Marine Biologics', 'marinebiologics.com', ''),
('MaRS Discovery District', 'marsdd.com', ''),
('Marunouchi Innovation Partners', 'marunouchi-innovation.com', ''),
('Mass Ventures', 'mass-ventures.com', ''),
('MassVentures', 'mass-ventures.com', ''),
('Mater AI', 'mater-ai.com', 'Medium'),
('Materials Nexus', 'materialsnexus.com', 'Medium'),
('Matter Venture Partners', 'mattervp.com', ''),
('Matwerkz', 'matwerkz.com', ''),
('Maxim Group', 'maximgrp.com', ''),
('McKesson', 'mckesson.com', ''),
('McKinsey', 'mckinsey.com', ''),
('MD Anderson', 'mdanderson.org', ''),
('MEDIC Life Sciences', 'medic-life-sciences.com', ''),
('Medical IP', 'medicalip.co.kr', ''),
('Meeting Mojo', 'meeting-mojo.com', ''),
('Mekanistic Therapeutics', 'mekanistictherapeutics.com', ''),
('Membravo', 'membravo.com', ''),
('Menlo Ventures', 'menlovc.com', ''),
('MEP Pro', 'meppro.co.uk', ''),
('Mercantile Companies', 'mercantilecompanies.com', ''),
('Mercury', 'mercury.com', ''),
('Meru Ventures', 'meruventures.com', ''),
('Mesh Bio', 'meshbio.com', ''),
('Metabolize', 'metabolize.life', ''),
('Metricpoint', 'metricpoint.info', ''),
('MG', 'mg-d0.substack.com', ''),
('MG Concrete', 'mgconcretelasvegas.com', ''),
('MHPS', 'mhps.co', ''),
('Michael Best', 'michaelbest.com', ''),
('Microsoft', 'microsoft.com', ''),
('Microsoft', 'msn.com', ''),
('Microsoft', 'hotmail.com', ''),
('Microsoft', 'outlook.mail.microsoft', ''),
('Microsoft', 'information.microsoft.com', ''),
('Midascopeqorva', 'app.midascopeqorva.com', ''),
('Millennium New Horizons', 'mnh.vc', ''),
('Mimic', 'mimic.systems', 'Low'),
('Ministerio de Economía', 'comercio.mineco.es', ''),
('Ministry of Foreign Affairs', 'mofa.go.kr', ''),
('Ministry of Health', 'moh.gov.bn', ''),
('Ministry of Port Authority (SG)', 'mpa.gov.sg/home', ''),
('Ministry of the Environment and Water Resources', 'mpa.gov.sg', ''),
('Mint Ventures', 'mintventures.bio', ''),
('Minutia', 'minutia.co', 'Low'),
('Mirae Asset Global', 'miraeasset.com', ''),
('Mirae Asset Securities', 'miraeassetsg.com', ''),
('Miraei', 'miraei.ai', ''),
('Mishrapedha', 'mishrapedha.awsapps.com', ''),
('Missouri State University', 'missouristate.edu', ''),
('Mistletoe', 'mistletoe.co', ''),
('Misty West', 'mistywest.com', ''),
('MIT', 'mit.edu', ''),
('Mitsubishi Hitachi Power Systems', 'mg.mhps.co', ''),
('ML Advisory', 'mladvisory.co', ''),
('Moderne Ventures', 'moderneventures.com', ''),
('Moelis', 'moelis.com', ''),
('Momentum Health Rehabilitation', 'momentumhrt.com.au', ''),
('Moogene', 'moogene.com', ''),
('Moogene Medi', 'moogene', 'Low'),
('Motion', 'usemotion.app', ''),
('Moulton', 'moulton.no', ''),
('Mount Therapeutics', 'mounttherapeutics.com', ''),
('MRANTI', 'mranti.my', ''),
('Mri Software', 'ng1v4.angus.mrisoftware.com', ''),
('MSQ Ventures', 'msqventures.com', ''),
('Mussel Polymers', 'musselpolymers.com', ''),
('N&E Innovation', 'vi-kang.com', 'Medium'),
('N2 Ventures', 'n2ventures.co', ''),
('Nabaco', 'nabaco.com', 'High'),
('Nairobi Lighting', 'nairobilighting.com', ''),
('Nakabayashi', 'nakabayashi-co.com', ''),
('Namic', 'namic.sg', ''),
('Nandina REM', 'nandinarem.com', ''),
('Nanogold Medtech', 'nanogoldmedtech.com', ''),
('Nanoingreen', 'nanoingreen.com', ''),
('Nanoweave', 'nanoweave.co', ''),
('Nanyang Biologics', 'nanyangbiologics.com', ''),
('Nate', 'nate.com', ''),
('National Academies of Sciences, Engineering, and Medicine', 'nationalacademies.org', ''),
('National Institutes of Health', 'nih.gov', ''),
('National University of Singapore', 'nus.edu.sg', ''),
('Naver', 'naver.com', ''),
('Navion Energy', 'navion.energy', ''),
('Neomab Bio', 'neomab-bio.com', ''),
('Neon Syndicate', 'neonsyndicateaustin.com', ''),
('Neosplice', 'neosplicetx.com', ''),
('nervoidai', 'nervoidai.net', ''),
('NetOrg', 'netorgft14806097.onmicrosoft.com', ''),
('Neu Battery', 'neumaterials.com', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));