WITH updates(name, domain, priority) AS (VALUES
('Wiharper', 'wiharper.com', ''),
('Wilberforce Global', 'wilberforceglobal.com', ''),
('Wild Microbes', 'wildmicrobes.com', 'Medium'),
('Winning Strategies Washington', 'wpllc.us', ''),
('Wittington Ventures', 'wittingtonventures.com', ''),
('Wix', 'notifications.wix.com', ''),
('Wix', 'emails.wix.com', ''),
('WNT Ventures', 'wntventures.co.nz', ''),
('Wolters Kluwer', 'wolterskluwer.com', ''),
('Wonik', 'wonik.com', ''),
('World Coffee Alliance', 'worldcoffeealliance.com', ''),
('Wosler', 'wosler.ca', ''),
('WOW Partners', 'wowpartners.net', ''),
('WowTale', 'wowtale.net', ''),
('Xaitherapeutics', 'xaitherapeutics.com', ''),
('Xeraya', 'xeraya.com', ''),
('Xeraya / Khazanah', 'xeraya.com', ''),
('YA Capital', 'yacapital.com', ''),
('Yale', 'yale.edu', ''),
('Yamaguchi Solutions', 'yamaguchi-ss.com', ''),
('yourcampusfund', 'yourcampusfund.com', ''),
('YPlasma', 'yplasma.tech', 'Medium'),
('Yuva Bio', 'yuvabio.com', ''),
('Zapier', 'send.zapier.com', ''),
('Zapier', 'mail.zapier.com', ''),
('Zayo Group', 'zayo.com', ''),
('Zeck', 'zeck.app', ''),
('Zenfold', 'zenfoldst.com', ''),
('zetachain', 'zetachain.com', ''),
('Zetapac', 'zetapac.com', ''),
('Zola Bio', 'zola.bio', ''),
('Zoom', 'zoom.us', ''),
('Zoom', 'e.zoom.us', ''),
('Zoro Tools', 'zoro.com', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));