WITH updates(name, domain, priority) AS (VALUES
('BIODEFENSE', 'biodefense.co', ''),
('Bioeconomy Corporation', 'bioeconomycorporation.my', ''),
('Biofit Event', 'biofit-event.com', ''),
('Biogenerator Ventures', 'biogeneratorventures.com', ''),
('BioMetallica', 'biometallica.com', 'Medium'),
('BioNTech', 'biontech.us', ''),
('bio-research', 'bio-research.ai', ''),
('Biostarks', 'biostarks.com', ''),
('biostarks', 'biostarks.com', ''),
('Biotools Innovator', 'biotoolsinnovator.org', ''),
('BistroChat', 'bistrochat.com', ''),
('bitBiome', 'bitbiome.bio', 'High'),
('Bitbiome', 'bitbiome.bio', ''),
('Bitbiome', 'bitbiome.co.jp', ''),
('Bix Restaurant', 'bixrestaurant.com', ''),
('BLA Regulatory', 'bla-regulatory.com', ''),
('Blackbox', 'blackbox.com.sg', ''),
('Blackwood Capital Partners', 'blackwoodcapitalpartners.com', ''),
('Blauwpark Partners', 'blauwparkpartners.com', ''),
('Blinq', 'blinq.me', ''),
('Block Dojo', 'blockdojo.io', ''),
('block71', 'block71.co', ''),
('Bloks', 'bloks.app', ''),
('BlueRun Ventures', 'blueruninvest.com', ''),
('Bluetide Capital', 'bluetidecapital.co', ''),
('Blunomy', 'theblunomy.com', ''),
('BluumBio', 'bluumbio.com', ''),
('Boon Referrals', 'boonreferrals.com', ''),
('Boston Atomics', 'bostonatomics.com', 'Low'),
('Boston Consulting Group', 'bcg.com', ''),
('BoxOne Ventures', 'boxone.xyz', ''),
('Branded Strategic', 'brandedstrategic.com', ''),
('Brekland', 'brekland.com', 'Low'),
('Brevo', '6731841.brevosend.com', ''),
('Brevo', '3939459.brevosend.com', ''),
('Brinter', 'brinter.com', ''),
('Brinter', 'brinter.com', ''),
('Brunei Economic Development Board', 'bedb.gov.bn', ''),
('Brunei Economic Development Board', 'bedb.gov.bn', ''),
('Brunei Investment Agency', 'bia.com.bn', ''),
('Bryosphere', 'bryosphere.ca/home', 'Low'),
('Business Development Bank of Canada', 'bdc.ca', ''),
('Business France', 'businessfrance.fr', ''),
('Bybug', 'bybug.io', ''),
('caasa', 'caasa.ca', ''),
('Cal Physical Therapy', 'cal-pt.com', ''),
('Calion Technologies', 'calion.tech', 'High'),
('Canadian Government', 'international.gc.ca', ''),
('Canopy', 'canopyaerospace.com', ''),
('Cantabio Pharmaceuticals', 'cantabio.com', ''),
('Canva', 'engage.canva.com', ''),
('Canva', 'account.canva.com', ''),
('Canva', 'canva.com', ''),
('Capricorn', 'capricornllc.com', ''),
('Capricorn', 'capricornllc.com', ''),
('Caproasia', 'caproasia.com', ''),
('Capro-X', 'capro-x.com', ''),
('Capro-X', 'capro-x.com', ''),
('Capture6', 'capture6.org', ''),
('Capture6', 'capture6.com', ''),
('Carbohyde', 'carbohyde.com', ''),
('Carbon Limiting Technologies', 'carbonlimitingtechnologies.com', ''),
('Carbonade', 'carbonade.co', ''),
('Carbonext', 'carbonextinc.com', ''),
('CARM', 'carm.or.kr', ''),
('Carta', 'team.carta.com', ''),
('Carta', 'carta.com', ''),
('Cartography', 'cartography.vc', ''),
('Cascade Bio', 'cascadebio.com', 'High'),
('Cascade Biocatalysts', 'cascadebiocatalysts.com', ''),
('Cascade Biosciences', 'cascadebio.com', ''),
('Castle Placement', 'castleplacement.com', ''),
('Castomize', 'castomize.co', 'Medium'),
('CatAmmon', 'finder.startupnationcentral.org/company_page/catammon', ''),
('CellMo', 'cellmoinc.com', 'High'),
('Cellmo', 'cellmoinc.com', ''),
('Cellular Agriculture', 'cell.ag', ''),
('CellWave Technologies', 'cellwavetech.com', ''),
('Celonis', 'make.com', ''),
('CERT Systems', 'co2cert.com', 'Low'),
('Certara', 'certara.com', ''),
('Cetogenix', 'cetogenix.co.nz', ''),
('CG Pharma', 'cgpharma.com', ''),
('CGenetix', 'cgenetix.com', ''),
('Chemfinity Tech', 'chemfinitytech.com', ''),
('ChemFinity Technologies', 'chemfinitytech.com', 'High'),
('ChemShift', 'chemshift.com', ''),
('Chemtbio', 'chemtbio.com', ''),
('Children''s Place', 'childrens.com', ''),
('China Live', 'chinalivesf.com', ''),
('Chip Eng Seng', 'chipengseng.com.sg', ''),
('Circleback', 'circleback.ai', ''),
('Cisema', 'cisema.com', ''),
('Citi', 'citi.com', ''),
('Citizens Bank', 'notifications.citizensbank.com', ''),
('Citizens Bank', 'privatebank.citizensbank.com', ''),
('Citizens Bank', 'em.citizensbank.com', ''),
('Citizens Bank', 'citizensbank.com', ''),
('Citizens of Humanity', 'citizensofhumanity.com', ''),
('Citizens Private Bank', 'citizensprivatebank.com', ''),
('CJ', 'cj.net', ''),
('Claud', 'claudnyc.com', ''),
('Claude', 'email.claude.com', ''),
('Clavystbio', 'clavystbio.com', ''),
('Clean Energy Ventures', 'cleanenergyventures.com', ''),
('Cleantech', 'cleantech.com', ''),
('Clear Creek Investments', 'clearcreekinv.com', ''),
('Clear Creek Investments', 'clearcreekinv.com', ''),
('ClearACH', 'clearach.com', ''),
('Clearach', 'clearach.com', ''),
('Clifford Chance', 'cliffordchance.com', ''),
('Climate Action', 'climateaction.org', ''),
('Climate Investment', 'climateinvestment.com', ''),
('Climatebase', 'climatebase.org', ''),
('CMI Data Hub', 'cmidatahub.com', ''),
('CO2Cert', 'co2cert.com', ''),
('CO2Tech', 'co2tech.com.au', ''),
('Cobi', 'cobi.tech', ''),
('Connect Group', 'connectgroup.global', ''),
('Connect Tan', 'connecttan.com', ''),
('Constellar', 'constellar.co', ''),
('Convergent Bio', 'convergent-bio.com', ''),
('Convergent VC', 'convergentvc.com', ''),
('Cooley', 'cooley.com', ''),
('Cornell University', 'cornell.edu', ''),
('Cornell University', 'ctl.cornell.edu', ''),
('CorpCap Global', 'corpcapglobal.com', ''),
('Corporate Capital Group', 'corpcapgrp.com', ''),
('Corporate Traveler', 'corporatetraveler.us', ''),
('Corporate Traveler', 'edm.corporatetraveler.us', ''),
('Cosmic Labs', 'cosmiclabs.space', ''),
('Cota Capital', 'cotacapital.com', ''),
('Craft Health', 'crafthealth.me', ''),
('Craftwrks', 'craftwrkscompany.com', ''),
('Craig Law Firm', 'thecraiglaw.com', ''),
('Crest Optics', 'crestoptics.com', ''),
('Critical Value', 'criticalvalueam.com', ''),
('Crosspoint Rx', 'crosspointrx.com', ''),
('Crosspoint Therapeutics', 'crosspointrx.com', 'Medium'),
('CSB Corporation', 'csb.co.jp', ''),
('CTK', 'ctkclip.com', ''),
('CTK USA', 'ctkusa.com', ''),
('CTVC', 'ctvc.co', ''),
('CTVC', 'ghost.ctvc.co', ''),
('CyanoCapture', 'cyanocapture.com', 'Medium'),
('Cytotronics', 'cytotronics.com', ''),
('Darwin Venture', 'darwin-venture.com.tw', ''),
('DC Finance', 'dc-finance.com', ''),
('DC Finance', 'dc-finance.com', ''),
('DC Finances', 'dcfinances.com', '')
)
UPDATE companies c SET
  website  = CASE WHEN u.domain   <> '' THEN u.domain   ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));