
WITH updates(name, domain, priority) AS (
  VALUES
('500 Global', '500.co', ''),
('100 Accelerator', '100accelerator.com', ''),
('1849 bio', '1849.bio', ''),
('2 Strands Biosciences', '2strandsbiosciences.com', ''),
('2S Water', '2swater.com', ''),
('3D BioFibR', '3dbiofibr.com', 'Low'),
('3D BioFibr.', '3dbiofibr.com', ''),
('3Helix', '3helix.com', ''),
('3M', 'mmm.com', ''),
('3R', '3r-t.com', ''),
('4ls Consulting', '4ls-consulting.com', ''),
('500 Global', '500.co', ''),
('5AM Ventures', '5amventures.com', ''),
('9zero', '9zero.com', ''),
('9Zero', 'letsgo.9zero.com', ''),
('A*STAR', 'hq.a-star.edu.sg', ''),
('A*STAR', 'a-star.edu.sg', ''),
('Aarti Pharma Labs', 'aartipharmalabs.com', ''),
('Abalone Bio', 'abalonebio.com', ''),
('ABL Bio', 'ablbio.com/en/company/main', ''),
('Abram Scientific', 'abramscientific.com', 'Medium'),
('AC Biode', 'acbiode.com', ''),
('Accelerated Materials', 'acceleratedmaterials.co', 'Medium'),
('Accor', 'accor.com', ''),
('Acipay Online', 'acipayonline.com', ''),
('Acrobat Genomics', 'acrobatgenomics.com', ''),
('Acrocyte', 'acrocyte.com', ''),
('Activate', 'activate.org', ''),
('Activate', 'activate.org', ''),
('Adapt Capital', 'adaptcapital.com', ''),
('ADB Ventures', 'adbventures.org', ''),
('ADEN Services', 'adenhq.com', ''),
('Adept Materials', 'adeptmaterials.com', 'Low'),
('Advantage Therapeutics', 'advantagetherapeutics.com', ''),
('Aepnus Technology', 'aepnus.com', ''),
('Affinity', 'affinity.co', ''),
('Affix Labs', 'affixlabs.com', ''),
('Agorize', 'agorize.com', ''),
('Agrata', 'agrata.co', 'Medium'),
('AI Therapies', 'ai-therapies.com', ''),
('AirAsia', 'notification.airasia.com', ''),
('AirREGI', 'airregi.jp', ''),
('Airtable', 'airtable.com', ''),
('Airtable', 'mail.airtable.com', ''),
('Ajinomoto Ventures', 'aj-cvc.com', ''),
('Al Riyad', 'alriyad.iq', ''),
('Albatroz Therapeutics', 'albatroztherapeutics.com', ''),
('Alchemist Accelerator', 'alchemistaccelerator.com', ''),
('Alkali Lab', 'alkalilabs.com', 'Medium'),
('Alkali Labs', 'alkalilabs.com', ''),
('Alkemio', 'alkemio.bio', ''),
('Alkemio-bio', 'alkemio.bio', 'Low'),
('Allium Bio', 'alliumbio.com', 'Medium'),
('Allvue Systems', 'allvuesystems.com', ''),
('Alpha Intelligence Capital', 'aicapital.ai', ''),
('AlphaMe', 'alphame.ai', ''),
('Alsop Louie Partners', 'alsop-louie.com', ''),
('Alta Resource Technologies', 'altatech.io', ''),
('Altos Ventures', 'altos.vc', ''),
('Altr', 'altrfltr.com', 'Medium'),
('Amazon', 'amazon.com', ''),
('Amazon', 'leo.amazon.com', ''),
('Amazon', 'amazonaws.com', ''),
('Amber Fusion Hub', 'amberfusionhub.com', ''),
('Amber Fusion Network', 'amberfusionnetwork.com', ''),
('American Concrete', 'americanconcreteonline.com', ''),
('AmiDi Group', 'amidigroup.com', ''),
('Ammax Bio', 'ammaxbio.com', ''),
('AmorePacific', 'apgroup.com/int/en', ''),
('Andreessen Horowitz', 'a16z.com', ''),
('Andrews Mixers', 'andrewsmixers.com', ''),
('Another Food Co.', 'anotherfood.co', 'Low'),
('Ansarada', 'ansarada.com', ''),
('Antares Ventures', 'antares.ventures', ''),
('Antarka', 'antarka.bio', 'Medium'),
('Anthology', 'anthology.net', 'Low'),
('Anthropic', 'email.anthropic.com', ''),
('Anthropic', 'mail.anthropic.com', ''),
('Antinori Napa Valley', 'antinorinapavalley.com', ''),
('Apellis', 'apellis.com', ''),
('Apex Group', 'apexgroup.com', ''),
('Apex Invest', 'events.apexinvest.io', ''),
('Apex Invest', 'apexinvest.io', ''),
('Apeximmune', 'apeximmune.com', 'Low'),
('APL Ventures', 'apl.ventures', ''),
('Apple', 'icloud.com', ''),
('Apple', 'me.com', ''),
('Apple', 'mac.com', ''),
('Applied Ventures', 'appliedventures.com', ''),
('Aquila Clouds', 'aquilaclouds.com', ''),
('Aragen', 'aragen.com', ''),
('Arc Group', 'arc-group.com', ''),
('Arcasa Science', 'arcascience.ai', ''),
('Arculus Solutions', 'arculus-solutions.com', ''),
('Arecor', 'arecor.com', ''),
('Aries Systems Corporation', 'aries.com', ''),
('Arlan Biotech', 'arlanbiotech.com', 'Low'),
('Arnold & Porter', 'arnoldporter.com', ''),
('Arovia', 'arovia.com', ''),
('ARPA-H', 'arpa-h.gov', ''),
('Arrakis', 'arrakis.bio', 'Medium'),
('Arrow Biome', 'arrowbiome.com', ''),
('Ascend', 'ascend.vc', ''),
('Ascendant Bio Capital', 'ascendantbiocapital.com', ''),
('Ashton Global', 'ashtonglobal.com', ''),
('Asian Development Bank', 'adb.org', ''),
('AsimicA', 'asimica.com', 'Low'),
('AsparaGlue', 'asparaglue.com', 'Low'),
('AT&T Mail', 'emaildl.att-mail.com', ''),
('Atlas Venture', 'atlasventure.com', ''),
('AtmoSpark Technologies', 'atmosparkh2.com', ''),
('AtoMe', 'atome.us', ''),
('Audio Vitality', 'audiovitality.com', ''),
('August GP', 'augustgp.com', ''),
('Avant Guard', 'avantguardinc.com', ''),
('Avenue Biosciences', 'avenuebiosciences.com', ''),
('Avisa Myko', 'avisamyko.com', 'Low'),
('Avnet', 'avnet.com', ''),
('Avnet', 'avnet.com', ''),
('Avstera Therapeutics Inc.', 'avstera.com', ''),
('Axon Energy', 'axonenergy.ai', ''),
('Ayrton Energy', 'ayrtonenergy.com', ''),
('Babson College', 'babson.edu', ''),
('Bain & Company', 'bain.com', ''),
('BANIQL', 'baniql.com', 'High'),
('Banyan', 'groupbanyan.com', ''),
('Banyan Tree', 'stay.banyantree.com', ''),
('Banyan Tree', 'banyantree.com', ''),
('BASF', 'basf.com', ''),
('Basketball Association of Singapore', 'nbas.org.sg', ''),
('Bay Area Times', 'bayareatimes.com', ''),
('BCA', 'bca.gov.sg', ''),
('bcengi', 'ping.bcengi.email', ''),
('Beehiiv', 'mail.beehiiv.com', ''),
('Beiley Biofund', 'beileybiofund.com/pages/english', ''),
('Bellcast Partners', 'bellcastpartners.com', ''),
('Beyond Bridge', 'beyondbridge.co', ''),
('BIA', 'bia.com.bn', ''),
('Big Blue', 'bigbluetec.com', 'Medium'),
('Big Blue Tech', 'bigbluetec.com', ''),
('Big Blue Technologies', 'bigbluetec.com', ''),
('Big Idea Ventures', 'bigideaventures.com', ''),
('Biip', 'biip-dcc.org', ''),
('Bikaner Advisors', 'bikaneradvisors.com', ''),
('Bio', 'bio.org', ''),
('Bio Technology Service', 'btsh2.com', 'Medium'),
('BioBoost', 'bioboostsynbio.com', ''),
('BioBreak', 'biobreak.org', ''),
('BioCentury', 'biocentury.com', ''),
('biocom', 'biocom.org', ''),
('BIODEFENSE', 'biodefense.co', ''),
('Bioeconomy Corporation', 'bioeconomycorporation.my', ''),
('Biofit Event', 'biofit-event.com', ''),
('Biogenerator Ventures', 'biogeneratorventures.com', ''),
('BioMetallica', 'biometallica.com', 'Medium'),
('BioNTech', 'biontech.us', ''),
('bio-research', 'bio-research.ai', ''),
('Biostarks', 'biostarks.com', ''),
('biostarks', 'biostarks.com', ''),
('Biotools Innovator', 'biotoolsinnovator.org', ''),
('BistroChat', 'bistrochat.com', ''),
('bitBiome', 'bitbiome.bio', 'High'),
('Bitbiome', 'bitbiome.bio', ''),
('Bitbiome', 'bitbiome.co.jp', ''),
('Bix Restaurant', 'bixrestaurant.com', ''),
('BLA Regulatory', 'bla-regulatory.com', ''),
('Blackbox', 'blackbox.com.sg', ''),
('Blackwood Capital Partners', 'blackwoodcapitalpartners.com', ''),
('Blauwpark Partners', 'blauwparkpartners.com', ''),
('Blinq', 'blinq.me', ''),
('Block Dojo', 'blockdojo.io', ''),
('block71', 'block71.co', ''),
('Bloks', 'bloks.app', ''),
('BlueRun Ventures', 'blueruninvest.com', ''),
('Bluetide Capital', 'bluetidecapital.co', ''),
('Blunomy', 'theblunomy.com', ''),
('BluumBio', 'bluumbio.com', ''),
('Boon Referrals', 'boonreferrals.com', ''),
('Boston Atomics', 'bostonatomics.com', 'Low'),
('Boston Consulting Group', 'bcg.com', ''),
('BoxOne Ventures', 'boxone.xyz', ''),
('Branded Strategic', 'brandedstrategic.com', ''),
('Brekland', 'brekland.com', 'Low'),
('Brevo', '6731841.brevosend.com', ''),
('Brevo', '3939459.brevosend.com', ''),
('Brinter', 'brinter.com', ''),
('Brinter', 'brinter.com', ''),
('Brunei Economic Development Board', 'bedb.gov.bn', ''),
('Brunei Economic Development Board', 'bedb.gov.bn', ''),
('Brunei Investment Agency', 'bia.com.bn', ''),
('Bryosphere', 'bryosphere.ca/home', 'Low'),
('Business Development Bank of Canada', 'bdc.ca', ''),
('Business France', 'businessfrance.fr', ''),
('Bybug', 'bybug.io', ''),
('caasa', 'caasa.ca', ''),
('Cal Physical Therapy', 'cal-pt.com', ''),
('Calion Technologies', 'calion.tech', 'High'),
('Canadian Government', 'international.gc.ca', ''),
('Canopy', 'canopyaerospace.com', ''),
('Cantabio Pharmaceuticals', 'cantabio.com', ''),
('Canva', 'engage.canva.com', ''),
('Canva', 'account.canva.com', ''),
('Canva', 'canva.com', ''),
('Capricorn', 'capricornllc.com', ''),
('Capricorn', 'capricornllc.com', ''),
('Caproasia', 'caproasia.com', ''),
('Capro-X', 'capro-x.com', ''),
('Capro-X', 'capro-x.com', ''),
('Capture6', 'capture6.org', ''),
('Capture6', 'capture6.com', ''),
('Carbohyde', 'carbohyde.com', ''),
('Carbon Limiting Technologies', 'carbonlimitingtechnologies.com', ''),
('Carbonade', 'carbonade.co', ''),
('Carbonext', 'carbonextinc.com', ''),
('CARM', 'carm.or.kr', ''),
('Carta', 'team.carta.com', ''),
('Carta', 'carta.com', ''),
('Cartography', 'cartography.vc', ''),
('Cascade Bio', 'cascadebio.com', 'High'),
('Cascade Biocatalysts', 'cascadebiocatalysts.com', ''),
('Cascade Biosciences', 'cascadebio.com', ''),
('Castle Placement', 'castleplacement.com', ''),
('Castomize', 'castomize.co', 'Medium'),
('CatAmmon', 'finder.startupnationcentral.org/company_page/catammon', ''),
('CellMo', 'cellmoinc.com', 'High'),
('Cellmo', 'cellmoinc.com', ''),
('Cellular Agriculture', 'cell.ag', ''),
('CellWave Technologies', 'cellwavetech.com', ''),
('Celonis', 'make.com', ''),
('CERT Systems', 'co2cert.com', 'Low'),
('Certara', 'certara.com', ''),
('Cetogenix', 'cetogenix.co.nz', ''),
('CG Pharma', 'cgpharma.com', ''),
('CGenetix', 'cgenetix.com', ''),
('Chemfinity Tech', 'chemfinitytech.com', ''),
('ChemFinity Technologies', 'chemfinitytech.com', 'High'),
('ChemShift', 'chemshift.com', ''),
('Chemtbio', 'chemtbio.com', ''),
('Children''s Place', 'childrens.com', ''),
('China Live', 'chinalivesf.com', ''),
('Chip Eng Seng', 'chipengseng.com.sg', ''),
('Circleback', 'circleback.ai', ''),
('Cisema', 'cisema.com', ''),
('Citi', 'citi.com', ''),
('Citizens Bank', 'notifications.citizensbank.com', ''),
('Citizens Bank', 'privatebank.citizensbank.com', ''),
('Citizens Bank', 'em.citizensbank.com', ''),
('Citizens Bank', 'citizensbank.com', ''),
('Citizens of Humanity', 'citizensofhumanity.com', ''),
('Citizens Private Bank', 'citizensprivatebank.com', ''),
('CJ', 'cj.net', ''),
('Claud', 'claudnyc.com', ''),
('Claude', 'email.claude.com', ''),
('Clavystbio', 'clavystbio.com', ''),
('Clean Energy Ventures', 'cleanenergyventures.com', ''),
('Cleantech', 'cleantech.com', ''),
('Clear Creek Investments', 'clearcreekinv.com', ''),
('Clear Creek Investments', 'clearcreekinv.com', ''),
('ClearACH', 'clearach.com', ''),
('Clearach', 'clearach.com', ''),
('Clifford Chance', 'cliffordchance.com', ''),
('Climate Action', 'climateaction.org', ''),
('Climate Investment', 'climateinvestment.com', ''),
('Climatebase', 'climatebase.org', ''),
('CMI Data Hub', 'cmidatahub.com', ''),
('CO2Cert', 'co2cert.com', ''),
('CO2Tech', 'co2tech.com.au', ''),
('Cobi', 'cobi.tech', ''),
('Connect Group', 'connectgroup.global', ''),
('Connect Tan', 'connecttan.com', ''),
('Constellar', 'constellar.co', ''),
('Convergent Bio', 'convergent-bio.com', ''),
('Convergent VC', 'convergentvc.com', ''),
('Cooley', 'cooley.com', ''),
('Cornell University', 'cornell.edu', ''),
('Cornell University', 'ctl.cornell.edu', ''),
('CorpCap Global', 'corpcapglobal.com', ''),
('Corporate Capital Group', 'corpcapgrp.com', ''),
('Corporate Traveler', 'corporatetraveler.us', ''),
('Corporate Traveler', 'edm.corporatetraveler.us', ''),
('Cosmic Labs', 'cosmiclabs.space', ''),
('Cota Capital', 'cotacapital.com', ''),
('Craft Health', 'crafthealth.me', ''),
('Craftwrks', 'craftwrkscompany.com', ''),
('Craig Law Firm', 'thecraiglaw.com', ''),
('Crest Optics', 'crestoptics.com', ''),
('Critical Value', 'criticalvalueam.com', ''),
('Crosspoint Rx', 'crosspointrx.com', ''),
('Crosspoint Therapeutics', 'crosspointrx.com', 'Medium'),
('CSB Corporation', 'csb.co.jp', ''),
('CTK', 'ctkclip.com', ''),
('CTK USA', 'ctkusa.com', ''),
('CTVC', 'ctvc.co', ''),
('CTVC', 'ghost.ctvc.co', ''),
('CyanoCapture', 'cyanocapture.com', 'Medium'),
('Cytotronics', 'cytotronics.com', ''),
('Darwin Venture', 'darwin-venture.com.tw', ''),
('DC Finance', 'dc-finance.com', ''),
('DC Finance', 'dc-finance.com', ''),
('DC Finances', 'dcfinances.com', ''),
('DC Partners', 'dcpartners.capital', ''),
('DCM Ventures', 'dcm.com', ''),
('D-CRBN', 'd-crbn.com', ''),
('De Novo Dairy', 'denovodairy.com', ''),
('Decile Hub', 'decilehubmail.com', ''),
('Decycle Bio', 'decycle.bio', ''),
('DeepSeq.AI', 'deepseq.ai', ''),
('Deerfield', 'deerfield.com', ''),
('Deimpact', 'deimpact.org', ''),
('Del Morgan & Co.', 'delmorganco.com', ''),
('Deloitte', 'deloitte.com', ''),
('Deloitte', 'deloitte.com', ''),
('Demy Colton', 'demy-colton.com', ''),
('Denka', 'denka.co.jp', ''),
('DEXMAT', 'dexmat.com', 'Medium'),
('Diesel Care', 'dieselcare.net', ''),
('Dify', 'dify.ai', ''),
('Dimov Tax', 'dimovtax.com', ''),
('DLF Hospitality', 'dlfhospitality.in', ''),
('DLG Law', 'dlglaw.co.kr', ''),
('DocuSign', 'docusign.net', ''),
('Donald Capital', 'donaldcapital-ny.com', ''),
('Dong-a Pharma', 'dapharm.com/en', ''),
('Doon Insights', 'dooninsights.com', ''),
('Draper University', 'draperuniversity.com', ''),
('Driven Plastics', 'drivenplastics.com', ''),
('Drooms', 'drooms.com', ''),
('Dropbox', 'docsend.com', ''),
('Drover Ventures', 'droverventures.com', ''),
('Duke University', 'duke.edu', ''),
('Dunn Innovations', 'dunninc.net', ''),
('dYdX Foundation', 'dydx.foundation', ''),
('Dynam Capital', 'dynamcapital.com', ''),
('E Evaluate', 'e.evaluate.com', ''),
('Earth Protex', 'earthprotex.com', ''),
('EBD Group', 'ebdgroup.com', ''),
('Eclipse Ventures', 'eclipse.vc', ''),
('Ecliptic Capital', 'eclipticcapital.com', ''),
('Eco-Business', 'eco-business.com', ''),
('Ecopha', 'ecopha.com', ''),
('Ecotech Capital', 'ecotechcap.com', ''),
('EDB (Economic Development Board)', 'edb.gov.sg', ''),
('EDBI', 'edbi.com', ''),
('Edinburgh Development Board', 'mail.edb.gov.sg', ''),
('EDM Enterprise', 'edm.enterprisesg.com.sg', ''),
('EFCAN', 'efcan.com.br', ''),
('Eff Consulting', 'effconsulting.com', ''),
('Effem', 'effem.com', ''),
('efishient', 'efishient.co.il', ''),
('Eigen', 'eigen.digital', ''),
('Elavon', 'elavon.com', ''),
('Electroflow Technologies', 'eflowtech.com', 'High'),
('Elev8 Venture Partners', 'elev8.vc', ''),
('Elevate Talent', 'elevatetaptalent.com', ''),
('Eli Lilly', 'lilly.com', ''),
('Elpis Biopharmaceuticals', 'elpisbiopharm.com', ''),
('elucidata', 'elucidata.io', ''),
('Elysia Bio', 'elysiabio.com', 'Medium'),
('eMart', 'emart.com', ''),
('Enavle', 'enavle.com', ''),
('Energy Impact Partners', 'eip.com', ''),
('Enervenue', 'enervenue.com', ''),
('Enmore', 'enmore.com', ''),
('Enmore Bio', 'global.enmorebio.com', ''),
('Enterprise Singapore', 'enterprisesg.gov.sg', ''),
('Envoy', 'envoy.com', ''),
('Eolic Wall', 'eolicwall.com', ''),
('Episteme Diagnostics', 'epistemedx.com', ''),
('eReceipt', 'ereceipt.usps.gov', ''),
('Eric Ripert', 'ericripert.com', ''),
('escoaster', 'escoaster.com', ''),
('Essentia', 'essentia.vc', ''),
('Essex', 'essex.com.sg', ''),
('EUC International', 'kg.euci.com', ''),
('EUC Solutions', 'ms.euci.com', ''),
('Eurasanté', 'eurasante.com', ''),
('Europcar', 'europcar.com', ''),
('Eva', 'evacorp.ai', ''),
('Eva Garland Consulting', 'evagarland.com', ''),
('Evaluate', 'info.evaluate.com', ''),
('Eventbrite', 'order.eventbrite.com', ''),
('Eventbrite', 'event.eventbrite.com', ''),
('Eventbrite', 'plans.eventbrite.com', ''),
('Eventbrite', 'campaign.eventbrite.com', ''),
('Eventbrite', 'email.eventbrite.com', ''),
('EventsHQ', 'exl.eventshq.com', ''),
('Evercloak', 'evercloak.com', ''),
('Evio', 'evio.asia', ''),
('EvolvedBio', 'evolved.bio', 'Medium'),
('EVV Portfolio', 'evvportfolio.com', ''),
('Exodys Energy', 'exodysenergy.com', 'Low'),
('Explori', 'mailer.explori.com', ''),
('Expostandzone', 'expostandzone.com', ''),
('Eztia', 'eztiahealth.com', ''),
('Fairmont Hotels & Resorts', 'fairmont.com', ''),
('Fathom', 'fathom.video', ''),
('FCC Singapore', 'fccsingapore.com', ''),
('FedEx', 'fedex.com', ''),
('Feon Energy', 'feonenergy.com', ''),
('Fermionic', 'fermionic.com', ''),
('Ferrum Technologies', 'ferrumtech.com', ''),
('Feynman Labs', 'feynmanlabs.sg', 'Medium'),
('FG Bradley''s', 'fgbradleys.com', ''),
('FibroCort Therapeutics', 'fibrocortherapeutics.com', ''),
('Field Ventures', 'fieldvc.com', ''),
('Fifth Innovation Oy', 'fifthinnovation.fi', ''),
('Fifth Wave Metals', 'fifthwavemetals.com', 'Medium'),
('Fillout', 'fillout.com', ''),
('FinCompliance', 'fincompliance.io', ''),
('Finsmes', 'finsmes.com', ''),
('Fireflies', 'fireflies.ai', ''),
('Firefly', 'firefly.com.my', ''),
('Fireflyz', 'fireflyz.com.my', ''),
('Flagship Pioneering', 'flagshippioneering.com', ''),
('Florida State University', 'chem.fsu.edu', ''),
('FlueVault', 'fluevault.com', 'Medium'),
('Fluxo', 'fluxomade.com', 'Low'),
('Fly Alliance', 'flyalliance.com', ''),
('Foley Hoag', 'foleyhoagllp.com', ''),
('Foley Hoag', 'foleyhoag.com', ''),
('Foray Bioscience', 'foraybio.com', ''),
('Force Family Office', 'forcefamilyoffice.com', ''),
('Forever Analytical', 'foreveranalytical.com', ''),
('Formidium', 'formidium.com', ''),
('Forta', 'forta.bio', ''),
('founders village', 'foundersvillage.co', ''),
('Freeflow', 'freeflow.io', ''),
('Frontier Bio', 'frontierbio.com', 'Medium'),
('Fuel Well Saver', 'fuelwellsaver.info', ''),
('Fujitsu', 'fujitsu.com', ''),
('Fuzionaire', 'fuzionaire.com', ''),
('G2', 'campaigns.g2.com', ''),
('Gaia Lens', 'gaia-lens.com', ''),
('galaxyuniverse', 'galaxyuniverse.ai', ''),
('Gardens by the Bay', 'gardensbythebay.com.sg', ''),
('Gardin', 'gardin.ag', 'Medium'),
('GCV Life', 'gcvlife.in', ''),
('GecKo Materials', 'geckomaterials.com', ''),
('GelSana', 'gelsanatherapeutics.com', ''),
('Gemseki', 'gemseki.com', ''),
('Gencat', 'gencat.cat', ''),
('General Catalyst', 'generalcatalyst.com', ''),
('General Inception', 'generalinception.com', ''),
('General Motors', 'gm.com', ''),
('General Sense', 'generalsense.com', ''),
('generalcontrol', 'generalcontrol.inc', ''),
('GENERIC', 'outlook.com', ''),
('geneva ppli', 'geneva-ppli.com', ''),
('Genome', 'genomecom.co.kr', ''),
('Genopole', 'genopole.fr', ''),
('GenZero', 'genzero.co', ''),
('GEVME', 'gevme.com', ''),
('GGV Capital', 'ggvc.com', ''),
('Ghadiscovery', 'email.ghadiscovery.com', ''),
('Gham', 'gham.com.sg', ''),
('GHL', 'e-ghl.com', ''),
('Ghost Management Group', 'ghost.wheresyoured.at', ''),
('Gilbert Home Comfort', 'gilberthomecomfort.com', ''),
('Giraffe Bio', 'giraffe-bio.com', 'Medium'),
('Giraffe Biosciences', 'giraffe-bio.com', ''),
('GlobalData', 'globaldata.com', ''),
('GoDaddy', 'godaddy.com', ''),
('Golden Hill Asset Management (GHAM)', 'gham.com.sg', ''),
('Gong', 'gong.io', ''),
('Goodwater Capital', 'goodwatercap.com', ''),
('Goodwood', 'goodwood.sg', ''),
('Google', 'gmail.com', ''),
('Google', 'group.calendar.google.com', ''),
('Google', 'google.com', ''),
('Google', 'accounts.google.com', ''),
('Google', 'googlemail.com', ''),
('GovDelivery', 'public.govdelivery.com', ''),
('Grain', 'grain.com.sg', ''),
('Granite Asia', 'graniteasia.com', ''),
('granola', 'mail.granola.so', ''),
('Greater Giving', 'online.greatergiving.com', ''),
('Green Willow', 'greenwillow.com.sg', ''),
('Greenitio', '', 'Medium'),
('Greenvelope', 'invites.greenvelope.com', ''),
('Greenvelope', 'greenvelope.com', ''),
('Grove Harbour Marina', 'groveharbourmarina.com', ''),
('GS Energy', 'gsenergy.co.kr', ''),
('GS Futures', 'gsfutures.vc', ''),
('GSK', 'gsk.com', ''),
('Gurryshark', 'gurryshark.com', ''),
('Halborn', 'halborn.com', ''),
('Hana Financial', 'hanafn.com', ''),
('Hand of God Wines', 'handofgodwines.ccsend.com', ''),
('Hanwha', 'hanwha.com', ''),
('Hartford Advisors', 'hartfordadvisorskyc.org', ''),
('Hartford Human Intelligence', 'hartford-humanintel.com', ''),
('Hazaiya', 'hazaiya.co.jp', ''),
('Heat Inverse', '', 'Low'),
('Helms Briscoe', 'helmsbriscoe.com', ''),
('Hemispherian', 'hemispherian.com', ''),
('Henkel', 'henkel.com', ''),
('Heritas Capital Management', 'heritas.com.sg', ''),
('Hexemb', 'hexemb.io', ''),
('High Tech', 'hight-tech.com', ''),
('Hight Tech', 'hight-tech.com', ''),
('HiT Nano', 'hitnanoinc.com', 'Medium'),
('Hiven', 'hiven.com.sg', ''),
('Holistic Solutions', 'hol.sg', ''),
('Honda Innovations', 'hondainnovations.com', ''),
('Horizons Ventures', 'horizons.com.hk', ''),
('Hospitality Headline', 'hospitalityheadline.com', ''),
('HubSpot', 'hubspot.com', ''),
('HubSpot', 'notifications.hubspot.com', ''),
('HubSpot', 'hubspotfree.na2.hs-send.com', ''),
('HubSpot', 'hubspotstarter.hs-send.com', ''),
('hubspot', 'hubspotstarter.na3.hs-send.com', ''),
('HubSpot', 'hubspotfree.hs-send.com', ''),
('Hummingbird Ventures', 'hummigbird.vc', ''),
('Hyatt', 'em.hyatt.com', ''),
('Hyatt', 'hyatt.com', ''),
('Hyatt', 'loyalty.hyatt.com', ''),
('Hyatt Hotels Corporation', 'm1.hpe-esp.hyatt.com', ''),
('HyperForge', 'hyperforge.co', ''),
('HyWatts', 'hywatts.com', 'Low'),
('IB Hospitality', 'ibhospitality.com', ''),
('IBK Korea', 'global.ibk.co.kr', ''),
('iConnections', 'iconnections.io', ''),
('Ideals', 'idealsvdr.com', ''),
('ignite_inv', 'ignite-inv.com', ''),
('IISolutions', 'iisolutions.ch', ''),
('Iktos', 'iktos.com', ''),
('Iland', 'iland6.com', ''),
('Ildong Pharma', 'ildong.com', ''),
('Illumina', 'illumina.cpa', ''),
('Illumina CPA', 'illuminacpa.clientportal.com', ''),
('Illumina Ventures', 'illuminaventures.com', ''),
('Imagina', 'imagina.com', ''),
('Imagina', 'imagina.io', ''),
('Immin Investment', 'imminvestment.com', ''),
('Immuno Biome', '', 'Low'),
('Immuse', 'immusetx.com', ''),
('IMNEWRUN', 'imnewrun.com', 'Low'),
('Impact Cooling', 'impactcooling.com', 'Medium'),
('Impact Cooling', 'impact-cooling.com', 'Medium'),
('Impact Cooling', 'impactcooling.com', ''),
('Impact Week', 'impactweek.com', ''),
('ImpriMedicine', 'imprimedicine.com', ''),
('Imre', 'imre.a-star.edu.sg', ''),
('Industrial Microbes', 'imicrobes.com', 'Medium'),
('Informa', 'informa.com', ''),
('Informa Connect', 'email.informaconnect.com', ''),
('Informa Connect', 'informaconnect.com', ''),
('ingo', 'ingo.me', ''),
('Inline', 'inline.tw', ''),
('INNOPOWER', 'innopower.com', ''),
('Innotek', 'innotek.lu', ''),
('Innovate360', 'innovate360.sg', ''),
('INSEAD', 'insead.edu', ''),
('Intactis', 'intactis.bio', 'Medium'),
('intelligence', 'intelligence.com', ''),
('Interactive Brokers', 'interactivebrokers.com', ''),
('Interactive Brokers', 'email.interactivebrokers.com', ''),
('Interactive Brokers', 'interactivebrokers.com.sg', ''),
('Interface Biosciences', 'interface.bio', ''),
('Intevity', 'intevity.com', ''),
('Intuit', 'em1.turbotax.intuit.com', ''),
('Intuit', 'intuit.com', ''),
('InventWood', 'inventwood.com', ''),
('Invest Seoul', 'investseoul.org', ''),
('Investible', 'investible.com', ''),
('Involved Events', 'involvedevents.com', ''),
('IOI Group', 'ioigroup.com', ''),
('Ionless', 'ionless.com', ''),
('Ionless Corporation', 'ionless.com', 'Medium'),
('iqt', 'iqt.org', ''),
('ISA Industrial', 'isaindustrial.com', ''),
('it-farm', 'it-farm.vc', ''),
('Ivim Technology', 'ivimtech.com', ''),
('Jack Richards Insurance', 'jackrichardsinsurance.com', ''),
('Jamie', 'hey.meetjamie.ai', ''),
('Jelawang Capital', 'jelawangcapital.com', ''),
('Jellatech', 'jellatech.com', 'Low'),
('JESUIS ELLE', 'jesuiselle.info', ''),
('JETRO', 'jetro.go.jp', ''),
('JK Advisory', 'jkadvisory.llc', ''),
('JLL', 'jll.com', ''),
('Johnson & Johnson', 'its.jnj.com', ''),
('Johnson & Johnson Innovation', 'jnjinnovation.com', ''),
('Jotform', 'jotform.com', ''),
('JPMorgan', 'jpmorgan.com', ''),
('JR Preston', 'jrpreston.com', ''),
('JTB Communication Design', 'jtbcom.co.jp', ''),
('JTC', 'jtc.gov.sg', ''),
('Jubilant Biosys', 'jubilantbiosys.com', ''),
('Jublia', 'jublia.co', ''),
('Just Private Tour', 'justprivatetour.com', ''),
('K2 Bio Capital', 'k2biocapital.vc', ''),
('Kaigene, Inc', 'kaigene.com', ''),
('Kajabi', 'y.kajabimail.net', ''),
('Karma', 'karmak.com', ''),
('Katapult', 'katapult.vc', ''),
('Keio MCC', 'keiomcc.com', ''),
('Kemwell Pharma', 'kemwellpharma.com', ''),
('Kindred Ventures', 'kindredventures.com', ''),
('Kinesiometrics', 'kinesiometrics.org', ''),
('Kitox', 'kitox.re.kr', ''),
('Knobbe', 'knobbe.com', ''),
('Koceco', 'koceco.co.kr', ''),
('Korea Bridging', 'koreabridging.com', ''),
('Korea University', 'korea.ac.kr', ''),
('Korea Venture Investment Corp.', 'kvic.or.kr', ''),
('Korean Air', 'koreanair.com', ''),
('Kortuc', 'kortuc.com', ''),
('KPBMA', 'kpbma.or.kr', ''),
('KROSSLINKER', 'krosslinker.com', ''),
('KSI Link', 'ksilink.com', ''),
('Kvicus', 'kvicus.com', ''),
('L.E.K. Insights', 'lekinsights.com', ''),
('L’Oreal', 'loreal.com', ''),
('LabStart', 'labstart.co', ''),
('Landmark Ventures', 'landmarkventures.com', ''),
('LawPay', 'appmailer.lawpay.com', ''),
('LCO', 'lco.legal', ''),
('Leap Ai', 'leap-ai.com', ''),
('Lee & Lee', 'leenlee.com.sg', ''),
('Lee Yin', 'leeyin.com.sg', ''),
('Lesaffre', 'lesaffre.com', ''),
('Leverage', 'leveragen.com', ''),
('LexisNexis Risk Solutions', 'lexisnexisrisk.com', ''),
('LG', 'lg.com', ''),
('LG Chem', 'lgchem.com/main/index', ''),
('LG Tech Ventures', 'lgtechventures.com', ''),
('Life Science Nation', 'lifesciencenation.com', ''),
('Lifespan Vision', 'lifespanvision.com', ''),
('Light Tech', 'light-tech.io', ''),
('Ligo Partners', 'ligopartners.com', ''),
('Limitless', 'limitless.network', ''),
('Lingotto Innovation Strategy', 'lingotto.com', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('LlamaIndex', 'llamaindex.ai', ''),
('Local Bounti', 'localbounti.com', ''),
('Longitude Capital', 'longitudecapital.com', ''),
('Loxegen', 'loxegen.net', ''),
('LSX Leaders', 'lsxleaders.com', ''),
('Lu. ma', 'lu.ma', ''),
('Luma', 'luma.com', ''),
('Luma Health', 'user.luma-mail.com', ''),
('Luma Mail', 'calendar.luma-mail.com', ''),
('Luma Mail', 'luma-mail.com', ''),
('Luminos Capital', 'luminoscapital.com', ''),
('Lunit', 'lunit.io', ''),
('Lux Capital', 'luxcapital.com', ''),
('Magnimind Academy', 'magnimindacademy.com', ''),
('Magnotherm Solutions', 'magnotherm.com', ''),
('Mahipono', 'mahipono.com', ''),
('Maia Farms', 'maiafarms.ca', ''),
('Mailchimp', '11114499.mailchimpapp.com', ''),
('Mailva', 'mailva.evite.com', ''),
('Make', 'us1.make.com', ''),
('Malaysia Airlines', 'malaysiaairlines.com', ''),
('Malaysian Research Accelerator for Technology and Innovation', 'mranti.my', ''),
('Mangusta Capital', 'mangustacap.com', ''),
('Mara Malabs', 'maramalabs.com', ''),
('Marama Labs', 'techbio', 'Medium'),
('Marine Biologics', 'marinebiologics.com', ''),
('MaRS Discovery District', 'marsdd.com', ''),
('Marunouchi Innovation Partners', 'marunouchi-innovation.com', ''),
('Mass Ventures', 'mass-ventures.com', ''),
('MassVentures', 'mass-ventures.com', ''),
('Mater AI', 'mater-ai.com', 'Medium'),
('Materials Nexus', 'materialsnexus.com', 'Medium'),
('Matter Venture Partners', 'mattervp.com', ''),
('Matwerkz', 'matwerkz.com', ''),
('Maxim Group', 'maximgrp.com', ''),
('McKesson', 'mckesson.com', ''),
('McKinsey', 'mckinsey.com', ''),
('MD Anderson', 'mdanderson.org', ''),
('MEDIC Life Sciences', 'medic-life-sciences.com', ''),
('Medical IP', 'medicalip.co.kr', ''),
('Meeting Mojo', 'meeting-mojo.com', ''),
('Mekanistic Therapeutics', 'mekanistictherapeutics.com', ''),
('Membravo', 'membravo.com', ''),
('Menlo Ventures', 'menlovc.com', ''),
('MEP Pro', 'meppro.co.uk', ''),
('Mercantile Companies', 'mercantilecompanies.com', ''),
('Mercury', 'mercury.com', ''),
('Meru Ventures', 'meruventures.com', ''),
('Mesh Bio', 'meshbio.com', ''),
('Metabolize', 'metabolize.life', ''),
('Metricpoint', 'metricpoint.info', ''),
('MG', 'mg-d0.substack.com', ''),
('MG Concrete', 'mgconcretelasvegas.com', ''),
('MHPS', 'mhps.co', ''),
('Michael Best', 'michaelbest.com', ''),
('Microsoft', 'microsoft.com', ''),
('Microsoft', 'msn.com', ''),
('Microsoft', 'hotmail.com', ''),
('Microsoft', 'outlook.mail.microsoft', ''),
('Microsoft', 'information.microsoft.com', ''),
('Midascopeqorva', 'app.midascopeqorva.com', ''),
('Millennium New Horizons', 'mnh.vc', ''),
('Mimic', 'mimic.systems', 'Low'),
('Ministerio de Economía', 'comercio.mineco.es', ''),
('Ministry of Foreign Affairs', 'mofa.go.kr', ''),
('Ministry of Health', 'moh.gov.bn', ''),
('Ministry of Port Authority (SG)', 'mpa.gov.sg/home', ''),
('Ministry of the Environment and Water Resources', 'mpa.gov.sg', ''),
('Mint Ventures', 'mintventures.bio', ''),
('Minutia', 'minutia.co', 'Low'),
('Mirae Asset Global', 'miraeasset.com', ''),
('Mirae Asset Securities', 'miraeassetsg.com', ''),
('Miraei', 'miraei.ai', ''),
('Mishrapedha', 'mishrapedha.awsapps.com', ''),
('Missouri State University', 'missouristate.edu', ''),
('Mistletoe', 'mistletoe.co', ''),
('Misty West', 'mistywest.com', ''),
('MIT', 'mit.edu', ''),
('Mitsubishi Hitachi Power Systems', 'mg.mhps.co', ''),
('ML Advisory', 'mladvisory.co', ''),
('Moderne Ventures', 'moderneventures.com', ''),
('Moelis', 'moelis.com', ''),
('Momentum Health Rehabilitation', 'momentumhrt.com.au', ''),
('Moogene', 'moogene.com', ''),
('Moogene Medi', 'moogene', 'Low'),
('Motion', 'usemotion.app', ''),
('Moulton', 'moulton.no', ''),
('Mount Therapeutics', 'mounttherapeutics.com', ''),
('MRANTI', 'mranti.my', ''),
('Mri Software', 'ng1v4.angus.mrisoftware.com', ''),
('MSQ Ventures', 'msqventures.com', ''),
('Mussel Polymers', 'musselpolymers.com', ''),
('N&E Innovation', 'vi-kang.com', 'Medium'),
('N2 Ventures', 'n2ventures.co', ''),
('Nabaco', 'nabaco.com', 'High'),
('Nairobi Lighting', 'nairobilighting.com', ''),
('Nakabayashi', 'nakabayashi-co.com', ''),
('Namic', 'namic.sg', ''),
('Nandina REM', 'nandinarem.com', ''),
('Nanogold Medtech', 'nanogoldmedtech.com', ''),
('Nanoingreen', 'nanoingreen.com', ''),
('Nanoweave', 'nanoweave.co', ''),
('Nanyang Biologics', 'nanyangbiologics.com', ''),
('Nate', 'nate.com', ''),
('National Academies of Sciences, Engineering, and Medicine', 'nationalacademies.org', ''),
('National Institutes of Health', 'nih.gov', ''),
('National University of Singapore', 'nus.edu.sg', ''),
('Naver', 'naver.com', ''),
('Navion Energy', 'navion.energy', ''),
('Neomab Bio', 'neomab-bio.com', ''),
('Neon Syndicate', 'neonsyndicateaustin.com', ''),
('Neosplice', 'neosplicetx.com', ''),
('nervoidai', 'nervoidai.net', ''),
('NetOrg', 'netorgft14806097.onmicrosoft.com', ''),
('Neu Battery', 'neumaterials.com', ''),
('Neurovanda', 'neurovanda.com', ''),
('Nevastar', 'nevastar.com', ''),
('New Summit Capital Advisors', 'newsummitcapadvisors.com', ''),
('New West Genetics', 'newwestgenetics.com', ''),
('New York University', 'nyu.edu', ''),
('Newco Capital Group', 'newcocapitalgroup.com', ''),
('Newfound Materials', 'newfoundmaterials.com', ''),
('Next Generation', 'nextgeneration.com', ''),
('Next Legacy', 'nextlegacy.com', ''),
('NexTeam Consulting', 'nexteamconsulting.com', ''),
('NextGen Ventures', 'nxtgen.vc', ''),
('Nexus Events', 'nexusevents.io', ''),
('NH Ventures', 'nhvic.com', ''),
('Nicholas', 'nicholas-esq.com', ''),
('Nifty', 'nifty.com', ''),
('Nina Mansfield', 'ninamansfield.com', ''),
('NitroFix', 'nitro-fix.com', ''),
('NLC Health', 'nlc.health', ''),
('Nobula', 'nobula3d.com', ''),
('Nomura Greentech', 'nomuragreentech.com', ''),
('Nona Technologies', 'nona-technologies.com', ''),
('nor1upgrades', 'nor1upgrades.com', ''),
('Northwest Area Council', 'nwacouncil.org', ''),
('Notion', 'mail.notion.so', ''),
('Novel Farms', 'novelfarms.co', ''),
('Novel Farms', 'novelfarms.co', ''),
('Noviscient', 'noviscient.com', ''),
('Nurasa', 'nurasa.com', ''),
('NVIDIA', 'nvidia.com', ''),
('Oak Ridge National Laboratory', 'mailer.ornl.gov', ''),
('Oak Ridge National Laboratory', 'ornl.gov', ''),
('Oberlin College', 'oberlin.edu', ''),
('OCMS', 'ocms.bio', ''),
('Octave Capital', 'octavecapital.co', ''),
('Octopus Group', 'octopusgroup.com', ''),
('Octopus Ventures', 'octopusventures.com', ''),
('ODC Life Sciences', 'odclifesciences.com', ''),
('Oji Group', 'oji-gr.com', ''),
('Okosix', 'okosix.com', ''),
('Oleo Sustainable POS', 'oleospos.com/home', 'Medium'),
('OmicInsight', 'omicinsight.com', 'Medium'),
('Omnicell', 'omnicell.com', ''),
('Oncodea', 'oncodea.com', ''),
('OncoPatch', 'oncopatch.net', 'Medium'),
('Oncoshot', 'oncoshot.com', ''),
('One Touch Tech Solutions', 'app.onetouchtechsolutions.com', ''),
('OneValley', 'theonevalley.com', ''),
('OpenAI', 'tm.openai.com', ''),
('OpenAI', 'email.openai.com', ''),
('OpenAI', 'tm1.openai.com', ''),
('OpenTable', 'opentable.com', ''),
('Organics Rx', 'organicsrx.com', ''),
('Orissa International', 'orissa-international.com', ''),
('Orochem Technologies', 'orochem.com', ''),
('Orrick', 'orrick.com', ''),
('Orrick', 'orricklaw.com', ''),
('Orrick', 'orrick.com', ''),
('Orum Therapeutics', 'orumrx.com', ''),
('Osome', 'osome.com', ''),
('Osome', 'mail.osome.com', ''),
('Otoro Energy', 'otoroenergy.com', ''),
('Otter', 'otter.ai', ''),
('Otter Bio', 'otter-bio.com', ''),
('Outcomes Fund', 'outcomes.fund', ''),
('Pacific Alliance Ventures', 'pav.vc', ''),
('Package Plus', 'package-plus.com/en-home', ''),
('Pai QBD', 'pai-qbd.com', ''),
('Paradromics', 'paradromics.com', ''),
('Park Road Advisors', 'parkroadadvisors.com', ''),
('Park West', 'parkwestllc.com', ''),
('Partnering', 'hellopartnering.com', ''),
('PartneringONE', 'partneringone.com', ''),
('Pathomics Health', 'pathomicshealth.com', ''),
('Pavilion Capital Ventures', 'pav.vc', ''),
('PCCW Solutions', 'netvigator.com', ''),
('PD1', 'pd1.onpdr.com', ''),
('Pear VC', 'pear.vc', ''),
('Pelecia', 'pelecia.com.br', ''),
('Perplexity', 'mail.perplexity.ai', ''),
('Pharmaventures', 'pharmaventures.com', ''),
('PheedLoop', 'pheedloop.com', ''),
('Philanthropy Asia Alliance', 'philanthropyasiaalliance.org', ''),
('Photosynthetic', 'photosynthetic.nl', 'Medium'),
('Phytogenesis', 'phytogenesis.com', 'Medium'),
('Phytolon', 'phytolon.com', ''),
('Piedmont Copy', 'piedmontcopy.com', ''),
('Pienaar', 'thepienaar.com', ''),
('Pillar VC', 'pillar.vc', ''),
('PillSafe', 'startpillsafe.com', ''),
('Pine Tree', 'pinetree.sg', ''),
('PineTree', 'pinetree.sg', ''),
('Pipestone Partners', 'pipestonepartners.com', ''),
('PitchBook', 'news.pitchbook.com', ''),
('PitchBook Data', 'pitchbook.com', ''),
('Planet Carbon', 'planetcarbon.earth', ''),
('Plantik Biosciences', 'plantik.bio', 'Medium'),
('Plasma BioWorks', 'plasmabioworks.com', ''),
('Plasmonica', 'plasmonica.com', 'Medium'),
('Plasmonica', 'plasmonica.com', ''),
('Pleno', 'plenoinc.com', ''),
('PlusAI', 'plusai.com', ''),
('PNPTC', 'pnptc.com', ''),
('Popl', 'getpopl.com', ''),
('POSCO', 'posco-inc.com', ''),
('Power Down Semiconductor', 'powerdownsemi.com', ''),
('Poze Caf', 'pozescaf.com', ''),
('Precise Health', 'precisehealth.io', ''),
('PredxBio', '', 'Medium'),
('Prelude Ventures', 'preludeventures.com', ''),
('Premium Technics', 'premiumtechnics.be', ''),
('PressWhot', 'presswhot.com', ''),
('Prestel and Partner', 'prestelandpartner.com', ''),
('Prestige Bio.', 'prestigebio.com', ''),
('Presto Labs', 'prestolabs.io', ''),
('Prime Outlier', 'primeoutlier.com', ''),
('PrismBio', 'prismbioinc.com', 'Medium'),
('ProAgni', 'proagni.com', ''),
('Prostate Cancer Foundation', 'pcf.org', ''),
('Protai', 'protai.bio', ''),
('Protheragen', 'protheragen.us', ''),
('Protheragen', 'protheragen.com', ''),
('Proton', 'proton.me', ''),
('Proton AG', 'pm.me', ''),
('PT Medicines', 'ptmedicines.com', ''),
('PTT ExpresSo', 'expresso.pttplc.com', ''),
('Purteq', 'purtecteam.com', ''),
('Putnam Insights', 'putnaminsights.com', ''),
('PVM', 'pvm.global', ''),
('Q Email Server', 'qemailserver.com', ''),
('QarboTech', 'qarbotech.com', ''),
('QDX', 'qdx.co', 'Medium'),
('Qualtrics', 'qualtrics-survey.com', ''),
('Quantivly', 'quantivly.com', ''),
('Quantum Leaps', 'qxl.jp', ''),
('QuestNow', 'questnow.net', ''),
('Quinn Emanuel', 'quinnemanuel.com', ''),
('Quinn Emanuel', 'quinnemanuel.com', ''),
('Quorum Bio', 'quorum-bio.com', ''),
('Qureator', 'qureator.com', ''),
('Qymune', 'qymune.com', ''),
('Radyus Research', 'radyusresearch.com', ''),
('Raidium', 'raidium.eu', ''),
('Raise Global', 'raiseglobal.co', ''),
('Rare Flora', 'rareflora.bio', ''),
('Rare Terra', 'rare-terra.com', ''),
('RB Growth Equity', 'rbgrowthequity.info', ''),
('RE:lumino', 'reluminotx.com', ''),
('Reactosome', 'reactosome.com', ''),
('Reactosome', 'reactosome.com', 'High'),
('Read AI', 'e.read.ai', ''),
('Redace Bio', 'redacebio.com', ''),
('REEgen', 'reegen.tech', ''),
('REEMAG LLC', 'reemag.net', ''),
('RegenXBIO', 'regenxbio.com', ''),
('Relumino Therapeutics', 'reluminotx.com', 'Medium'),
('Remember', 'rememberapp.co.kr', ''),
('Reneubio', 'reneubio.com', 'Medium'),
('Repair Biotechnologies', 'repairbiotechnologies.com', ''),
('Replit', 'replit.com', ''),
('Replit', 'mail.replit.com', ''),
('Resend', 'notifications.resend.com', ''),
('Resend', 'updates.resend.com', ''),
('Retinovo', 'n/a', 'Low'),
('ReviveMed', 'revivemed.io', 'Low'),
('Revivo Biosystems', 'revivobio.com', ''),
('Revopsis', 'revopsis.com', ''),
('RevOpsis Therapeutics', 'revopsis.com', ''),
('Rialto Patrol', 'rialtopatrol.com', ''),
('Rigid Robotics', 'rigidrobotics.com', 'Low'),
('Riva Huerta Abogados', 'rivashuertaabogados.mx', ''),
('Riverbridge Capital', 'riverbridgecap.com', ''),
('Roca Water', 'rocawater.com', 'Medium'),
('Rocamaterials', 'rocamaterials.com', ''),
('Rockefeller University', 'rockefeller.edu', ''),
('Rockz Consulting', 'rockzconsulting.com', ''),
('Rooter Man', 'rooterman.com', ''),
('Rosalind', 'rosalinddx.com', ''),
('Royal Brunei Airlines', 'mail.flyroyalbrunei.com', ''),
('Royal Brunei Airlines', 'flyroyalbrunei.com', ''),
('Rushnu', 'rushnu.com', ''),
('RWTH Aachen', 'win.rwth-aachen.de', ''),
('S&P Global', 'spglobal.com', ''),
('S&P Global Packaging', 'spglobalpkg.com', ''),
('S2G Ventures', 's2gventures.com', ''),
('Sabancı ICT', 'sabancict.com', ''),
('Sage Boardroom', 'sageboardroom.com', ''),
('Sage Healthcare', 'sagehealthcare.com', ''),
('Sage3', 'sage3.com', ''),
('Samsung Ventures', 'samsungventure.co.kr/english/jsp/investment/sector.jsp', ''),
('San Francisco Court Appointed Special Advocates', 'volunteer.sfcasa.org', ''),
('San Francisco Wine Society', 'sanfranciscowinesociety.com', ''),
('Satin Corp', 'satincorp.com', ''),
('SATS', 'sats.com.sg', ''),
('SATS', 'sats.com.sg', ''),
('SCAI Therapeutics', 'scaitrx.com', ''),
('Scale Climate', 'scale-climate.org', ''),
('SCF Global', 'scf-global.com', ''),
('Schneider Electric', 'se.com', ''),
('Schneider Electric', 'se.com', ''),
('SciClone', 'sciclone.com', ''),
('Scindo', 'scindo.bio', 'High'),
('SciSemi', 'scisemi.com', ''),
('SciTech Development', 'scitechdevelopment.com', ''),
('Scoot', 'itinerary.flyscoot.com', ''),
('Scoot', 'notify.flyscoot.com', ''),
('SDTA', 'sdta.org.sg', ''),
('Sealed Air', 'sealedair.com', ''),
('Sedgwick Yard', 'sedgwickyard.com', ''),
('Seed Engineers', 'seedengineers.com', ''),
('SEEDS Capital', 'sggc.sg', ''),
('Seeds Capital', 'seedscapital.sg', ''),
('Seeds Capital', 'seedscapital.sg', ''),
('Seek Labs', 'seeklabs.com', ''),
('Seia Bio', 'seiabio.com', ''),
('Selta Square', '', 'Low'),
('SendFox', 'sendfoxmail.com', ''),
('Seoul National University', 'snu.ac.kr', ''),
('Seppure', 'seppure.com', 'Medium'),
('Sequoia Capital', 'sequoiacap.com', ''),
('Serenity Power', 'serenitypower.ca', 'Low'),
('Setherapeutics', 'setherapeutics.com', ''),
('SevenRooms', 'message.sevenrooms.com', ''),
('SevenRooms', 'email.sevenrooms.com', ''),
('SGGC', 'sggc.sg', ''),
('SGInnovate', 'sginnovate.com', ''),
('Sharp Corporation', 'sharp.co.jp', ''),
('Shimizu Corporation', 'shimz.co.jp', ''),
('Shinhan', 'shinhanvc.com/en', ''),
('Shinsegae / Emart', 'shinsegae.com', ''),
('SHMD', 'shmd.io', ''),
('Shopify', 'g.shopifyemail.com', ''),
('Shorewind Capital', 'shorewindcapital.com', ''),
('Sidley', 'sidley.com', ''),
('Sift Biosciences', 'siftbios.com', 'High'),
('Sightera Biosciences', 'sightera-biosciences.com', ''),
('silkit ltd.', 'silkit-bio.com', ''),
('Silverwood Capital', 'silverwoodcapital.com', ''),
('Silverwood Partners', 'silverwoodpartners.com', ''),
('Sime Darby Property', 'simedarbyproperty.com', ''),
('Sina', 'vip.sina.com', ''),
('Singapore Airlines', 'contact.singaporeair.com', ''),
('Singapore Airlines', 'singaporeair.com', ''),
('Singapore Airlines', 'email.singaporeair.com', ''),
('Singapore Airlines', 'flightinfo.singaporeair.com', ''),
('Singapore Airlines', 'singaporeair.com.sg', ''),
('Singapore Global Network', 'email.singaporeglobalnetwork.gov.sg', ''),
('Singapore Management University', 'smu.edu.sg', ''),
('Singapore Polytechnic', 'sp.edu.sg', ''),
('SingHealth', 'singhealth.com.sg', ''),
('Sixline Semi', 'sixlinesemi.com', ''),
('SixLine Semiconductor', 'sixlinesemi.com', 'Low'),
('SK', 'sk.com', ''),
('skeletonkey', 'skeletonkey.vc', ''),
('Skouria', 'skouria.com', ''),
('Sky VC', 'sky-vc.com', ''),
('SkyDeck', 'skydeck.vc', ''),
('SkyNano', 'skynanotechnologies.com', ''),
('Slack', 'slack.com', ''),
('Slack Mail', 'slack-mail.com', ''),
('snatchedventures', 'snatchedventures.com', ''),
('Snobol', 'snobol.com', ''),
('Social Innovation Summit', 'socialinnovationsummit.com', ''),
('Sofitel', 'sofitel.com', ''),
('Solar Steam', 'solarsteam.ca', ''),
('SOLETAIR POWER Oy', 'soletairpower.fi', ''),
('Sompo Japan Kii', 'sompo-japan-kii.com', ''),
('SOSV', 'sosv.com', ''),
('SOSV', 'sosv.com', ''),
('SOSV Matchups', 'emails.sosvmatchups.com', ''),
('Sound Financial Management', 'sfinvman.com', ''),
('South Sound Behavioral Hospital', 'southsoundbehavioralhospital.com', ''),
('Spacee', 'spacee.co.jp', ''),
('sparklabs', 'sparklabsgroup.com', ''),
('Spartha Medical', 'sparthamedical.eu', ''),
('Sparton Capital', 'sparton.capital', ''),
('Sparxell', 'sparxell.com', 'High'),
('Sparxell', 'sparxell.com', ''),
('Spectrum Impact', 'spectrum-impact.org', ''),
('Splash Tools', 'splash.tools', ''),
('SPMB', 'mg.spmb.com', ''),
('Springboard Enterprises', 'springboardenterprises.org', ''),
('Square', 'messaging.squareup.com', ''),
('Squarespace', 'mail.squarespace.com', ''),
('St Ambroise', 'st-ambroise.com', ''),
('Stage', 'stage.ac', ''),
('Stanford', 'stanford.edu', ''),
('Startup Career Advice', 'startupcareeradvice.com', ''),
('Startup Grind', 'startupgrind.com', ''),
('Station F', 'stationf.co', ''),
('Station F', 'stationf.co', ''),
('Station F', 'stationf.co', ''),
('Stein Law', 'steinlawllc.com', ''),
('Stellar Communications', 'stellarcommunications.net', ''),
('Stern', 'stern.nyu.edu', ''),
('Steve Hubbard Real Estate', 'stevehubbardrealestate.com', ''),
('STH Biotech', 'sth-biotech.com', 'Medium'),
('Stibee', 'send.stibee.com', ''),
('Stripe', 'stripe.com', ''),
('StrongBody', 'strongbody.ai', ''),
('Substack', 'substack.com', ''),
('Sumitomo Chemical', 'sumichem.com', ''),
('Sumitomo Trust', 'sumithk.com', ''),
('Summit Agricultural Partners', 'summit-ap.com', ''),
('Summit Automotive Partners', 'summit-ap.com', ''),
('Sun Metalon', 'sunmetalon.com', ''),
('Sunbird Bio', 'sunbirdbio.com', ''),
('Suncelmo', 'suncelmo.co.jp', ''),
('Sungreen H2', 'sungreenh2.com', ''),
('Super Carb', 'supercarb.tech', 'Medium'),
('Supercool Earth', 'supercool-earth.com', 'Low'),
('Superhuman Ventures', 'superhumanventurescorp.com', ''),
('supermomos', 'supermomos.com', ''),
('Supervision Partners', 'supervisionpartners.com', ''),
('Swiss Biotech', 'swissbiotech.org', ''),
('Switch.', 'switchsg.org', ''),
('Swoogo', 'swoogo.com', ''),
('SWS Investments', 'sws-inv.com', ''),
('SXD', 'sxd-ai.com', ''),
('Syenta', 'syenta.com', ''),
('Synanthra', 'synanthra.com', 'Medium'),
('Synconize', 'umail.synconize.cn', ''),
('Synovance', 'synovance.com/en', 'Low'),
('Tabor Capital', 'taborcapital.com', ''),
('Tabsquare', 'tabsquare.com', ''),
('Tactiq', 'tactiq.io', ''),
('Tahaluf', 'event.tahaluf.com', ''),
('Tahaluf Al Emarat Technical Solutions', 'e.tahaluf.com', ''),
('Taiga', 'taigakorea.com', ''),
('Tanaka Manufacturing Co.', 'ml.tanaka.co.jp', ''),
('Targtex', 'targtex.com', ''),
('Taros Chemicals AG', 'taros.de', ''),
('TCV', 'tcv.com', ''),
('TDI Sustainability', 'tdi-sustainability.com', ''),
('TEAM LEWIS', 'teamlewis.com', ''),
('Tech Week', 'tech-week.com', ''),
('Tech40', 'tech40.net', ''),
('Teema Group', 'teemagroup.com', ''),
('Temasek', 'temasek.com.sg', ''),
('Temasek', 'temasek.com.sg', ''),
('Temasek Foundation', 'temasekfoundation.org.sg', ''),
('Temasek Foundation', 'temasekfoundation.org.sg', ''),
('TeOra Bio', 'teoralife.com', 'High'),
('Terasaki Institute for Biomedical Innovation', 'terasaki.org', ''),
('Terra Oleo', 'terraoleo.com', 'High'),
('Terrain Capital', 'terraincapital.com', ''),
('Tersa', 'tersa.earth', 'Low'),
('Thai Oil Public Company Limited', 'thaioilgroup.com', ''),
('The Biz Dev Wizard', 'thebizdevwizard.com', ''),
('The company associated with the domain dwtc.com is Dubai World Trade Centre.', 'dwtc.com', ''),
('The company name is Brevo.', '9508868.brevosend.com', ''),
('The company''s name is Dropbox.', 'em-s.dropbox.com', ''),
('The Dev Wizard', 'thedevwizard.com', ''),
('The Empire', 'theempirebrunei.com', ''),
('The name of the company is Education Digital Bureau.', 'email.edb.gov.sg', ''),
('The Real Care', 'thereal.care', ''),
('The Regal Team', 'theregalteam.com', ''),
('The Rocket Science Group', '38665077.mailchimpapp.com', ''),
('The Work Boulevard', 'theworkboulevard.com', ''),
('Thea Energy', 'thea.energy', 'Low'),
('Thea Energy', 'thea.energy', ''),
('ThermoBionics', '', 'Low'),
('TheWell Bioscience', '', 'Low'),
('THINK BIOSCIENCE', '', 'Low'),
('Tiamat Sciences', 'tiamat-sciences.com', ''),
('tideview', 'tideviewfo.com', ''),
('Tierra Biosciences, Inc.', '', 'Low'),
('Tikva Allocell', 'tikvaallocell.com', ''),
('TippingPoint Biosciences', 'tippingpointbiosciences.com', 'Medium'),
('Toast', 'toast-restaurants.com', ''),
('Tock', 'exploretock.com', ''),
('Top Harvest Capital', 'topharvestcap.com', ''),
('Top Tier Impact', 'toptierimpact.com', ''),
('TOP Ventures (Thai Oil)', 'topventures.co.th', ''),
('Toronto Metropolitan University', 'cloudmail.torontomu.ca', ''),
('Toronto Metropolitan University', 'torontomu.ca', ''),
('TPC House', 'tpchouse.com', ''),
('Trail Bio', 'trailbio.com', ''),
('Transition Biomining', 'transition.bio', 'Medium'),
('TransLink', 'translink.kr', ''),
('Translink Capital', 'trankslinkcapital.com', ''),
('Trend Micro', 'tmes.trendmicro.eu', ''),
('Tripleseat', 'tripleseat.com', ''),
('Tripleseat', 'discussions.tripleseat.com', ''),
('Trirec', 'trirecpl.com', ''),
('Trisail Medical', 'trisailmedical.com', ''),
('Truffle', 'truffle.com', ''),
('Truist', 'truist.com', ''),
('TrustYou', 'trustyou.com', ''),
('TTV Capital', 'ttv.vc', ''),
('Turk Telekom', 'turktelekom.com.tr', ''),
('Type6 Therapeutics', 'type6tx.com', 'Medium'),
('UCEA', 'ucea.pt', ''),
('UDN Group', 'udngroup.com', ''),
('Uluu', 'uluu.com.au', ''),
('U-Member', 'u-member.com.cn', ''),
('UniBio', 'unibaio.com', ''),
('United Airlines', 'united.com', ''),
('Univ UBS', 'univ-ubs.fr', ''),
('Universal Materials Incubator (UMI)', 'umi.co.jp/en', ''),
('University of California, Berkeley', 'berkeley.edu', ''),
('University of California, San Francisco', 'ucsf.edu', ''),
('University of Colorado Anschutz Medical Campus', 'cuanschutz.edu', ''),
('University of Texas at Austin', 'che.utexas.edu', ''),
('University of Toronto', 'utoronto.ca', ''),
('UNKNOWN', 'justinscholz.de', ''),
('Upcyclex', 'upcyclex.tech', ''),
('Valence Capital', 'valuencecap.com', ''),
('Valley Research Park', 'valleyresearchpark.com', ''),
('Vanderbilt University', 'vanderbilt.edu', ''),
('Vector AIS', 'vectorais.com', ''),
('Venture News', 'news.vntr.vc', ''),
('ventureLAB', 'venturelab.ca', ''),
('Venuerific', 'venuerific.com', ''),
('Verde Nanomaterials', 'verdenano.com', ''),
('Verimmune', 'verimmune.com', ''),
('Vertex Holdings', 'vertexholdings.com', ''),
('Vibe Bio', 'vibebio.com', ''),
('Vickers Venture', 'vickersventure.com', ''),
('Vilota', 'vilota.ai', ''),
('Vimcal', 'mail.vimcal.com', ''),
('Vinteriors', 'vinteriorskc.com', ''),
('Viologen', '', 'Medium'),
('Virfold', 'virfold.io', ''),
('Viridis', 'viridisresearch.com', ''),
('Visible', 'visible.vc', ''),
('VisitCloud', 'visitcloud.com', ''),
('Vita Coco', 'vitacoco.com', ''),
('VMS Ireland', 'vmsireland.com', ''),
('Voodoo', '2021.somosvoodoo.com', ''),
('Voyager VC', 'voyagervc.com', ''),
('VqResearch', 'vqresearch.com', ''),
('Vridhi Home Finance', 'vridhihomefinance.com', ''),
('Walter and Eliza Hall Institute of Medical Research', 'wehi.edu.au', ''),
('Washington University in St. Louis', 'wustl.edu', ''),
('Wasna', 'wasna.co', 'Low'),
('Wave', 'waveapps.com', ''),
('Wayfinder Bio', 'wayfinderbio.com', ''),
('Wayfinder Bio', 'wayfinderbio.com', 'Medium'),
('Wealthing', 'wealthing.vc', ''),
('Web Summit', 'websummit.com', ''),
('Weebly', 'promote.weebly.com', ''),
('Weehur', 'weehur.com.sg', ''),
('Weeloy', 'weeloy.com', ''),
('Weizmann Institute of Science', 'weizmann.ac.il', ''),
('Westport Alpha', 'westportalpha.com', ''),
('Westwood Aerogel', 'westwoodaerogel.com', ''),
('Weybridge Partners', 'weybridge.partners', ''),
('WGroup', 'wgrou.com', ''),
('wheresyoured', 'wheresyoured.at', ''),
('Whitworth University', 'whitworth.edu', ''),
('Wiharper', 'wiharper.com', ''),
('Wilberforce Global', 'wilberforceglobal.com', ''),
('Wild Microbes', 'wildmicrobes.com', 'Medium'),
('Winning Strategies Washington', 'wpllc.us', ''),
('Wittington Ventures', 'wittingtonventures.com', ''),
('Wix', 'notifications.wix.com', ''),
('Wix', 'emails.wix.com', ''),
('WNT Ventures', 'wntventures.co.nz', ''),
('Wolters Kluwer', 'wolterskluwer.com', ''),
('Wonik', 'wonik.com', ''),
('World Coffee Alliance', 'worldcoffeealliance.com', ''),
('Wosler', 'wosler.ca', ''),
('WOW Partners', 'wowpartners.net', ''),
('WowTale', 'wowtale.net', ''),
('Xaitherapeutics', 'xaitherapeutics.com', ''),
('Xeraya', 'xeraya.com', ''),
('Xeraya / Khazanah', 'xeraya.com', ''),
('YA Capital', 'yacapital.com', ''),
('Yale', 'yale.edu', ''),
('Yamaguchi Solutions', 'yamaguchi-ss.com', ''),
('yourcampusfund', 'yourcampusfund.com', ''),
('YPlasma', 'yplasma.tech', 'Medium'),
('Yuva Bio', 'yuvabio.com', ''),
('Zapier', 'send.zapier.com', ''),
('Zapier', 'mail.zapier.com', ''),
('Zayo Group', 'zayo.com', ''),
('Zeck', 'zeck.app', ''),
('Zenfold', 'zenfoldst.com', ''),
('zetachain', 'zetachain.com', ''),
('Zetapac', 'zetapac.com', ''),
('Zola Bio', 'zola.bio', ''),
('Zoom', 'zoom.us', ''),
('Zoom', 'e.zoom.us', ''),
('Zoro Tools', 'zoro.com', '')
)
UPDATE companies c
SET
  website  = CASE WHEN u.domain  <> '' THEN u.domain  ELSE c.website  END,
  priority = CASE WHEN u.priority <> '' THEN u.priority ELSE c.priority END
FROM updates u
WHERE LOWER(TRIM(c.name)) = LOWER(TRIM(u.name));
